#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: 2020 Was Not "Unprecedented"
categories: take history covid19
---
#+end_export

"2020 was an unprecedented year because ...". All of us can find several phrases to complete that
sentence. Versions of this quote have been circulating for more than a year. In particular, creators
on YouTube and News announcers love this quote; every turn in the economy and the things they are
able to / unable to do in their lives is "unprecedented". In her book "This Time Is Different",
Reinhart makes the argument that there is *a compulsive urge* to claim that the present is
completely different from the past, that there are no similarities and that whatever challenge /
victory came *yesterday* is different and more significant than something that happened a *10 years
ago*. Reinhart rejects this practice of turning every *insight* into an *epiphany* and points to the
fact that the same type of financial crises keep happening, over and over again, to demonstrate that
the present is no more special than the past.

#+begin_export html
<!--more-->
#+end_export

A lot has happened in the *first 20 years of the 21st Century*: devastating terrorist attacks in
several major cities across the world (New York, London, Mumbai, Hyderabad, Boston, Paris), wars in
several countries in the Middle East, the recognition of a possible climate crisis that could have
very bad outcomes for countries that don't have the resources to adapt, encroachment into sovereign
countries by ambitious states that aim to expand their sphere of influence, the rise of the Internet
and the substantial increase in Internet penetration across the world.

A lot happened in the *20th Century*: 2 World wars, a deadly epidemic (Spanish Flu), a prolonged
period of heightened tensions and anxiety, decline of monarchies and the rise of democracies,
collapse of the colonial powers and freedom in their colonies, the discovery of significant crude
oil deposits in the Middle East, rise of the personal computer, numerous healthcare breakthroughs,
highly integrated world trade and an increase in the average number of allies of a country (2.5
1900-1950, 10.5 1950-2000).

A lot happened in the *19th Century*: 17 major wars between 1815 and 1914 in Europe alone, the
persecution of colonies by colonial powers, Japan went through the Meiji restoration and expanded
it's empire into Korea and parts of China, Jane Austen wrote some of her best novels.

A lot happened in the *18th Century:* 33 major wars between 1715 and 1815, the founding of America
as a constitutional democracy, ...

These are just a few of the events from memory, references in the books I read over the past few
months, and my experience since 2005. Historians would be able to lay out these centuries in a more
logical, articulate manner (They would also be able to remember more things that happened in the
18th century, where my memory has not served me well). My argument here is that *things happen all
the time*. They happened 300 years ago, and they happened yesterday. One should undoubtedly look at
the things that are happening in one's life as events from which *unique insights* can be garnered,
but one should not make the mistake of believing that these events are *unprecedented*.

My favorite example of this is the invention of the Printing press by Gutenberg in the mid-15th
century (1446-1450). Between the late 15th Century and the late 16th Century, book prices went down
90%: In about 2 generations (life expectancy was low), the price of books had become 1/10th in real
terms (i.e. removing the impact of inflation on the prices). Also, recent economic impact studies
have shown that the impact of the printing press on society was larger than that of the personal
computer between 1977 and 2004. The major difference being that the PC's impact was much faster (40
years as against the 140 years it took the Printing Press to be propagated across the world). I
imagine myself being 15 years old in 1450, when Gutenberg made his breakthrough. In the next 40
years, book prices would have gone down by nearly half. *That* sounds very much like an
unprecedented event, but I hesitate to give that tag to anything. Especially when dealing with the
present, one should take special precaution as they have not yet had the luxury to analyze the
events in retrospect.

The other misconception that I have seen thrown around is that the period since the end of WW2 in
1945 has been relatively peaceful. In objective terms, this might have been the case as life
expectancy has gone up and infant mortality has gone down across the world. Rosling makes a
compelling case in his book, Factfulness. But aggregate statistics seldom serve as accurate
reflections of all the people in the world the world (even though they are useful to represent
progress on a timescale longer than 75 years).

The Cold war was not actually "cold" and the post-WW2 period was not peaceful for the people in
Korea, Vietnam or [[https://www.atomicheritage.org/history/proxy-wars-during-cold-war-africa][Congo]]. The US and USSR acted as proxy powers in several countries in Africa, Asia
and the Middle East (CIA orchestrated coups). The type of warfare changed from trench warfare, the
norm during WW1 and WW2, to guerrilla warfare, required to root out the insurgencies of the 20th
century. Nevertheless, the facts remained unchanged for people in the countries that were stuck
fighting a war: *death, displacement and destruction*.

On the economic front, the 20th Century also saw some major upheaval: Germany was reunified in 1990
after 4 decades of separation. The reunification was followed by a decade of European soul
searching, as various countries in Europe tried to signal their commitment to the bloc; this effort
culminated in the formation of the European Union and the adoption of a common currency in the early
2000s.

India's economic policy saw major changes in 1991 and the economy was opened up to foreign
investment and products, the monopolies in the automobile and electronics industries were brought to
an end. The impacts of this policy change have been long reaching. State-owned enterprises that were
created *after* the globalization of the economy (like BSNL) have struggled and continue to face a
government that wishes to privatize these businesses. This indicates another major limitation from
not being able to analyze the event in retrospect: One is unable to properly analyze the *side
effects*.

#+begin_export html
<hr/>
#+end_export

Before assigning the dubious distinction of "[[https://abcnews.go.com/Politics/unprecedented-named-peoples-choice-2020-word-year-dictionary/story?id=74735664][unprecedented]]" to something, it is worth pausing to
think about whether this take would be valid a year, 5 years, a decade or a century from now. The
telegraph shortened physical distance like never before; the Internet blew the telegraph out of the
water. I am convinced that the sober approach of *not* saying that something is unprecedented is the
way to go when analyzing the present.
