#+TITLE: My experience with partiality in school sports
#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: My experience with partiality in school sports
categories: bias life childhood
---
#+end_export

When I was about 12 years old, I was in school in Mumbai. At the school, I was in the Basketball
team. I started playing the sport without any special reason; it was something to do. As I played
the sport, I discovered that I was particularly good at some of the defensive positions (mainly
because I was able to run faster than everyone else who was at the same school in my age group: an
exceedingly small sample). This discovery was a revelation to me. I believed that the connection
between "skill" and "success" was real: I believed that my coach would see that I had talent and
pick me to play in regional matches. This didn't happen; in fact, I remember being picked only once
during my 5 years on the team. This is not a _sob story_. I wish I _did_ feel bad about it, I wish I
felt like I had been wronged, so that I could talk about _recovering_ from that place. I don't feel
like that at all; I look back at that phase of my life as an amusing few years. This post is an
exploration of my feelings about what happened then and how I make sense of it now.

#+begin_export html
<!--more-->
#+end_export

In my school, there was a pecking order, like in every school and institution out there. In my
basketball team, seniority was everything. The earlier you started practicing with the team, the
better your chances of getting the coach's attention. There were about 20 people who would attend
most practices and were dedicated to the sport. In any basketball game, 5 people play on the court
at any given time. Frequent substitutions were common for our team, and in actual matches which we
played against other schools from the same city / district / state, the coach decided what
substitutions to make. So, at the top of the pecking order, was the basketball coach, below it were
some of the people who were in the "Under 16 (U-16)" age group and had been practicing for several
years, then there were some of the junior people, like me, who had been a part of the team for only
a couple years at that point, and finally, some people who had just joined the team and would likely
drop out after a few weeks.

The practice schedule was relaxed. We practiced for about an hour each day. There were most of the
typical parts of any basketball team's practice sessions: Lay-ups, running, mock matches,
three-point shoots and free-throw practice. The mock matches were the most exciting. I lived for
those; they gave me the adrenaline rush that I craved: A real match, with a clock and real opponents
(even if they were pretend opponents on your team).

Some of this was great fun. It was the first time I had friendships with people who were older than
me, who had more "life experience" (whatever that means for a 12 year old). I remember one
particular occasion when it was raining heavily and I had gone to practice, arriving completely
drenched, only to learn that practice had been canceled. I don't know why this particular instance
stuck with me, perhaps because of my belief that I was a diligent member of the team.

Some of it was not so much fun: I was lightly bullied by some of the older people on the team who
were not very good but had stuck on simply because of their seniority and dedication. I had a few
run-ins with some of the other "favored" players on the team who were good at offense and generally
pissed when I played some part in making them look like a fool on the court. The adult supervision
was limited and I was tiny (about 150 cms, 40 kgs). I remember only a couple instances when the
altercation became physical. I wasn't _damaged_ in any sense due to all of this. I am certainly
proud that I didn't give in to the bullies and continued to play the best that I could on the court.

I remember distinctly the coach's *partiality* when picking people to play in actual matches. It was
the first time I had run into anything of this sort. I was good at studies and that generally meant
favorable attention from my teachers, and consequently, favorable outcomes when there were
selections for things like the regional Mathematics Olympiad.

My run-ins with partiality were *frustrating* and I felt *helpless*. Several years later, I still
remember this feeling well: Being *convinced* that the coach was making the wrong move when he
picked someone to play, certain that I could do a better job. When we went to other schools to play
in regional matches, the coach would *pick the same people over-and-over*, irrespective of how
dismal their performance in the previous week/day/match.

This behavior was inexplicable; maybe he was just incompetent; maybe he chose the same people
over-and-over because he believed that they gave him the best chance at winning; or maybe, he was in
denial, convinced that his judgment was flawless despite all evidence to the contrary. At school, we
called this kind of bias *partiality*. I have heard about similar experiences from most of my
friends who went to school in India. I hear about this from my younger cousins who are in school
now. We would talk about partiality when people were selected to be a part of the school's quiz
team, or to go to another city to participate in a debate. This list is endless. When I asked my
parents why this kind of thing happened, they would tell me about the oft-repeated tenet: *Life
isn't fair; [[https://www.youtube.com/watch?v=TnlPtaPxXfc][that's life]]*. I accepted this principle, and embraced it, without knowing how to deal
with the fallout.

We didn't win many matches. The one time that I played in an actual match, I must have been on the
court for about 10 minutes of the total 40 minutes, I don't remember accomplishing anything
match-changing. We lost that one too. Two things stood out, about this particular loss.

First, I *wasn't jubilant* that I had been picked to play; I didn't even tell my parents that I had
been on the court, it felt like a trivial detail.(My parents suspected that I rarely got
picked. They were content to know that I had had a good trip and didn't press me for details. I am
eternally grateful to them for that. I don't think it would have done me any good if I had provided
them the details, or if they had tried to console me, or asked the coach to pick me more often).

Second, that loss didn't hit me any harder than the ones that I had watched from the
sidelines. Every loss felt the same *irrespective of whether I had been on the court*. I was not
able to write off the other losses as something I didn't have much to do with, nor did I feel more
responsible for the loss, when I was the one on the court. It was always a strange experience to get
back on the bus and travel back to our school. Everyone was mostly sad about the match, but we were
also happy about getting to go somewhere, experience the world *alone*, _almost_ like
adults (Turns out Michael Scott was right about [[https://www.tvfanatic.com/quotes/i-guess-this-is-what-they-call-a-bittersweet-moment-it-is-bitte/][bittersweet experiences]]).

This visceral experience with bias at a young age jaded me, I think. I found it easier to shrug off
future losses and failures as just unfortunate strokes of luck. Today, looking back, I can see that
I forged the path to where I am. I also like to think that I have tried my best to prevent and be
aware of bias in my dealings with others.

*P.S.* I am writing about this after about a decade and if any of the "romanticizing the past
instinctively" business is true, then the "good" parts that I talked about were decidedly worse than
I portrayed them.
