#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: "Hazing: Motives and countermeasures: An abstract analysis"
categories: university college institutions
---
#+end_export

#+begin_quote
The point of hazing is to make the victims of the hazing want to haze the next class of victims
-- [[https://www.bloomberg.com/opinion/articles/2021-03-18/goldman-analysts-work-too-hard][Levine on analysts at Goldman]]
#+end_quote

This got me thinking about my experience with bullying during childhood and hazing in college. I
turned out "okay": I escaped the worst of it by laying low. I laughed at the parts that I
found hilarious. I ridiculed the people who were hazing me. I looked around and found (rather
easily) some of their peers, who also ridiculed them and were incomparably _better_ than them (in my
estimation). I endured what I could find no way out of. And I enabled the subsequent classes of
victims to escape it.

On graduating college and entering a new phase of my life, old bonds where cherished and new
friendships were formed; belonging was felt and people _cared_. With the benefit of hindsight, I
consider the question of hazing once more.

#+begin_export html
<!--more-->
#+end_export

* Why do people engage in hazing?

Think as I might, I am unable to come up with a single, satisfying justification for it. Here are
some candidates:

1. *Hazing is a power trip:* Just as the immigration officer adjudicating the entry of thousands of
   tourists asks them questions and forces them to do things that don't serve any apparent
   purpose[fn:1] before stamping their passport, so can the seniors inside a hostel reinforce their
   power through hazing. They are big fish in a small pond; a perverse pleasure can be gained from
   harassing others. Safe in their beliefs that juniors can do nothing against this harassment, that
   institutions don't have the right controls to curb it and ignorant of the extent of their soft
   power, seniors take full advantage of their position
2. *Cycle of abuse:* "I was hazed, and hence I shall haze". Even among those who seem to have
   experienced the underlying nature of the world, this argument holds considerable purchase. Often,
   this argument is framed as "I was hazed and it is only fair for me to try it out and see if it
   makes me feel better" or "I was hazed and I think it made me more resilient. Thus, it is my duty
   to pass this on". I can say unequivocally that this argument *betrays* a damning lack of
   identity, morality and first principles, the things that are eternally true irrespective of the
   situation
3. *Hazing builds community:* This is an elegant argument from the abuser's point of
   view: They convince themselves that they are bringing the victims together; pushing them closer
   by putting them all through the same kind of hardship, playing the part of the proverbial "lunch
   lady" whom they will rant about in weeks to come. The formation of a bond that would not have
   existed in the absence of this external _stimulus_ is unnecessary, and the bond thus formed *will
   not* survive long. The community that is supposedly built is merely an illusion that abusers who
   don't have the stomach to face up to what they are doing conjure. Communities are built through
   warmth, empathy and companionship in the time of need; *not* through abuse for abuse's sake.
4. *Hazing builds character:* The abuser engages in artful deception. They wash themselves clean of
   responsibility by declaring, "I can credit myself for the _characters_ that I have built
   today". I have heard seniors boasting about former students who "made" it in the real world, whom
   they admire and want to emulate; the glaring lack of self-identity is completely unnoticed by
   these admirers.
5. *Hazing is a necessity for the bond between institutions and students:* The presumption with this
   argument is that the "Hostel" or the "College" that one attends is an institution whose
   relationship with the students who live or study in it is tenuous, like the branches of a tree in
   autumn whose branches stand ready to snap at the mildest gust of wind. I think this is true:
   Hostels are not endearing places, they are not comfortable, welcoming or well provisioned for
   living a _good_ life; the food is horrible and the hygiene one wouldn't write home about. One
   might remember the time spent there with nostalgia and affection, one might even visit with
   family, but one does not want to go back for an extended period of time. If the bond is
   tenuous, *why should one reinforce it through abuse?* Indeed, the fact that one has to resort to
   abuse to preserve a bond that would break if left to it's own devices should give the abuser
   pause: What is it that you are trying to achieve by prolonging the bond through such cruel means?
6. *Hazing makes people resilient to future hardships:* Yes, on the surface, I admit this is true. In
   the pedestrian sense, anything that has been dealt with before is easier to deal with in the
   future. If one has dealt with abuse in the past, then they will fare better at dealing with abuse
   in the present. Does this tell us that we should intentionally put others through hardship, so
   that they might be better prepared for the future? *Of course not*, that is absurd. As Seneca
   reminds us, the stoic aims to remain unaffected no matter what happens by rehearsing the
   worst-case scenarios in his mind; this exercise has nothing to do with his experience of those
   worse-case scenarios.

All these justifications leave something to be desired for. They don't clarify the question. Reading
through these again, I feel a false comfort arising from having enumerated some possible root
causes; I want the reader to be wary of this: We are hovering near the periphery; but we have *not*
found the root cause.

* Why don't institutions put a stop to it?

Functionaries and officials at every college and university know that hazing is going on, and yet
they do nothing. It is well within their power to stamp it out; I am sure there are educational
institutions which have rid themselves of it completely. Why does the average institution stand
silently by?

1. *Institutions don't _really_ care:* This is not a dig at institutions; rather it's a dig at
   adults in society. As one grows older, all institutions care less and less about them and expect
   them to lead an independent, _transactional_ life. All around the world, discussions about the
   social safety net are reaching a fever pitch in the higher income countries; while the merits of
   old-age homes are discussed openly in middle-income countries. Ezra Klein's June 2020 AMA on The
   Ezra Klein Show has a poignant quote about this: "From taking care of my son, a toddler, it has
   become exceedingly clear to me that we should treat everyone around us the way that we treat
   children: When I speak to him, I say the things that would benefit him. I don't want to be
   vindictive; I don't expect to be treated the way that I treat him; I am able to act with empathy
   without having to make a conscious effort to do so" (paraphrased).
2. *Institutions do care, but they have _better_ things to do:* This will be
   familiar to people working in Agile teams where "priority" is assigned to every task and some
   tasks in the Backlog never get done because they were never "high priority enough". Most
   government-funded colleges are not run very efficiently and they are not under any obligation to
   improve their efficiency. My belief is that colleges have a surplus of staff and an unwillingness
   to do anything, like governments. A good demonstration of institutions getting their priorities
   horribly wrong was the paving of a parking lot at the Mechanical engineering department at IIT
   Kharagpur; while the department did not have air conditioning in any of the classrooms or a
   decent canteen. Assigning higher priority to the former rather than the latter is a gross misuse
   of public funds and a misunderstanding of the majority's needs. Further, like the members of the
   Select committee trying to understand why an expensive [[https://www.youtube.com/watch?v=dIto5mwDLxo][roof garden]] was commissioned by
   questioning a bureaucrat, it is impossible to understand this decision. Trying to understand it
   have left me only with futile frustration.
3. *Institutions are delegating some of their work to willing seniors:* This is a controversial
   argument; the gist is that institutions *do* want someone to supervise the new students who are
   coming into the campus and ensure that they don't get into trouble through "too much freedom"
   (whatever that is); but they are unable or *unwilling* to perform this supervisory function and
   are delegating it to other students who are willing to _take up_ this mantle and work for the
   institution for free. In return, these seniors are rewarded with positions in the "Student
   government" which gives them a false sense of importance which they use to legitimize their
   harassment as a "good deed".
4. *Society has given up and accepted the existence of hazing:* This is the most defeatist
   reason. There are several things that we have just accepted, there is not much debate on the
   topic because the debates seem to go nowhere and the conclusions are fait accompli: "Yes,
   Institutions should put a stop to hazing.", "Yes, Governments should enact legislation and
   seriously pursue punitive action".  Few have the incentive to become an activist advocating for
   these topics as their impact is low in the utilitarian sense: "Just endure it for the first year
   of college, it will build character and you will understand more about the real world", or my
   personal favorite, "What you are going through is nothing compared to what *I* went through; so
   don't complain" etc. The other two star examples of this are (a) Governments, everyone is
   perpetually unhappy with them, but at least they are passably good at their primary
   responsibility, [[https://www.youtube.com/watch?v=cIYfiRyPi3o][maintaining stability]], and (b) Economic inequality, everyone acknowledges the
   existence of economic inequality and its evils, the activists on the two extremes are screaming
   at the top of their voices for either the Free market or Socialism. In this cacophony of voices,
   everyone remains unheard and governments don't have any incentive to take action as they will be
   unable to take credit or use it to forge a path to reelection.

* How do you deal with hazing?

Moving away from the abstract, this is a question that I want to give a satisfying answer to. I used
3 strategies back in college:

1. *Maintain a low profile:* During the period that you are going to be hazed, make yourself
   non-existent. I spent as little time as possible around people I didn't trust or suspected would
   haze me at some point in the future; this includes not becoming too familiar with them (there is
   a misconception that if you are familiar with the seniors you will not be harassed as much; I
   have found the opposite to be true). Eventually, everyone will get trapped in their net and this
   happened to me as my implementation of this strategy was not sound. When seniors went on rounds
   through the hostel floor that I was living on and screamed like banshees at juniors for
   disrespecting them by not assembling in the common room, I committed an error and made myself
   noticeable. I stood up to them and refused to go down to the common room saying I had to "study
   for an upcoming examination"[fn:2]. They were not having any of it and I lost that
   battle. Retrospectively, it occurred to me that I was reinforcing their power trip by giving them
   an opportunity to wield the power for real.
2. *Do something worthwhile:* This is a general suggestion that applies to all the time that one spends at college. During
   the period that you are going to be hazed, focus on something worthwhile that is not academics
   and not social media. Whatever it might be, it will give you the perspective required to look
   past the shortsightedness of the people hazing you and come to terms with how pointless their
   exercise is and how pathetic it is that they don't see that futility. For me, this was
   *reading*. I read a lot of novels during this time (like Dickens' Great Expectations) and managed
   to find solace in the struggles of the protagonists and their clear-eyed opposition of their
   fictional tormentors.
3. *Find and participate in a group with seniors who ridicule hazing:* At my college, the
   seniors who engaged in hazing were a minority of their peers. I found several of their peers who
   ridiculed them and let me vent my frustrations to them: What seemed pointless to me, they had
   already overcome. I see that they were playing the role of a manager: they were absorbing my
   anxieties and frustrations and reflecting back the wisdom that comes with experience and a
   broader worldview.

-----

*Footnotes:*

[fn:1] Going through immigration at Munich in August 2019, I was asked by the immigration officer to
show him that I had the 600 euros, that I claimed to have, for the vacation that I was about to
embark upon. An _interesting_ start to a vacation.

[fn:2] I should have known better than to use an academic reason against people who barely thought
about it and believed that anyone who _did_ think about academics needed to be reformed.
