#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: "America: An Unreliable Ally"
categories: america politics democracy
---
#+end_export

The American political system is /strange/. It has three branches; the Executive, Congress and the
Judiciary. Judges within the judiciary are appointed by the Executive with approval from
Congress. The President is the highest official in the Executive branch and elected directly by the
people. And all members of Congress are also directly elected. All the lawmaking power lies with
Congress and it is [[https://www.nytimes.com/2021/06/28/upshot/medicaid-expansion-democrats-obamacare.html][/generally/ very hard to repeal laws]] which have already been enacted. On the
other hand, the Executive branch is a fickle-minded body where the current President's whims and
fancies are the primary deciding force. Treaties are signed by the Executive branch. And wars begin
and end at the Executive branch's will. This makes America an unreliable republic to have any kind
of long-term agreement with.

#+begin_export html
<!--more-->
#+end_export

Democracies crave [[https://youtu.be/cIYfiRyPi3o?t=137][stability]]. Economies are the most important things that governments manage, and
long-term economic policy can be drafted only when one's allies are clearly known and their behavior
can be reliably anticipated or they can be trusted to give sufficient warning of major policy
changes. There are more problems that governments generally want to solve like providing the right
amount of nutrition to citizens and enabling access to modern healthcare, emanating from Research
and Development efforts in allied countries. All these things hinge upon a reliable ally.

The US-UK relationship is [[https://uk.usembassy.gov/our-relationship/policy-history/][special]][fn:1]. This in turn makes sudden policy changes such as Brexit in
UK [[https://www.theguardian.com/world/2021/sep/22/us-uk-special-relationship-faces-new-challenges-despite-signs-of-healing][difficult]] to navigate for the allied country. Similarly, the abrupt American exit from
Afghanistan left Britain in a strange spot. They discovered that refugees from the war-torn country
were going to come to various countries in Europe and might soon be eligible to travel to and work
on British soil. This puts the policies that both countries have for their own countries in
jeopardy, as these sudden excess/deficient flows of goods and people will drive a wedge through
established policy.

The Executive branch signs treaties which the Executive branch is free to leave. The reversal is
/not at all/ stunning, and in fact, is the obvious solution to an ideological disagreement. If your
predecessor entered a deal that you believe is not a good one, *just leave.* Being in the powerful
position of being the largest economy and a leader among English-speaking nations (which covers most
of the world, due to British colonial history), the US seldom has to worry about *actual* impacts
inside America.

I stress the word *actual* here because the Media coverage will insist on the "stunning policy
reversals," even though a self-interested actor (such as a politician) will think of this reversal
as the obvious step. Journalists seem to have a soft-spot for symbolic moves. I am incensed by this
false emphasis on "symbols" within policy, where the final policy that gets enacted is what matters,
and everything else is /just fluff./ (/Sidenote:/ The US government is good at creating fluff: Biden
managed to [[https://morningconsult.com/2021/04/27/biden-100-days-global-views-america/][improve his approval ratings]] abroad within just 3 months of taking office. This approval
rating abroad started falling later in his presidency though. And the global media is exceptional at
consuming fluff, both of the self-aggrandizing sort and otherwise.)

Obama entered the Iran Nuclear Deal and the Paris Climate Accords in 2015. Both of these were touted
to be a big deal[fn:2] at the time and for several years after the fact. Trump took office and
swiftly moved to get out of both deals. He gave various reasons for his departure. From the point of
view of other parties to this treaty, the reasons are immaterial and no amount of ridiculing
Trump[fn:3] or the Republican Party is of any real use. The consequential decision had already been
made.

Finally, going further in from foreign policy to America's domestic stance on issues, Biden's famous
[[https://www.msn.com/en-us/news/politics/what-did-president-biden-e2-80-99s-day-one-executive-orders-achieve/ar-BB1cVZov]["executive order" purge]] on his first day in office was another symbolic move that served to confirm
America's unreliable status as a "partner" in anything. I was surprised that the Biden
administration made a big deal about directly reversing 9 Trump executive orders; this kind of
/stunning/ policy reversal is the last thing other partners want to see.

With a falling approval rating [[https://projects.fivethirtyeight.com/biden-approval-rating/?ex_cid=rrpromo][at home]] and [[https://morningconsult.com/form/global-leader-approval/#section-49][abroad]] and an inability to build a consensus for [[https://www.cbsnews.com/news/biden-climate-plan-cut-build-back-better/][domestic
policy]], the Biden administration has failed at their [[https://www.state.gov/dipnote-u-s-department-of-state-official-blog/america-is-back-president-biden-outlines-his-vision-for-u-s-foreign-policy/]["America is Back"]] campaign. Facing a grueling
mid-term election in just 1 year, in which they [[https://fivethirtyeight.com/features/our-best-tool-for-predicting-midterm-elections-doesnt-show-a-republican-wave-but-history-is-on-the-gops-side/][are projected]] to lose control of Congress, it is
questionable that any significant policy will be enacted in Biden's remaining presidential term.

However, this is in no way a hindrance for people that want to see America do something big: the
Judiciary branch's top body, the Supreme Court, [[https://www.nytimes.com/2021/10/03/us/politics/supreme-court-new-term.html][has just begun]] a term with some very big cases
scheduled. And Congress is probing both Facebook and Google for (what I approximate to) /shady
monopolistic business-running behavior./

[fn:1] "The United States has no closer ally than the United Kingdom, and British foreign policy
emphasizes close coordination with the United States."

[fn:2] I can not comprehend why a climate agreement where countries set non-binding targets which
they can choose not to adhere to is a big deal. But hey, your local journalist says its a big deal
and so it is.

[fn:3] Colbert's coverage of Trump was vitriolic and unwatchable during most of this period.
