#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Victorian-era Dining Hall Etiquette
categories: iit-kgp india orientation-program
series_id: orientation-program-at-iit-kgp
---
#+end_export

Food holds a special importance in everyday life. A lot of memories are connected to it and
apparently [[https://archive.ph/UH8oH#selection-859.33-859.86][the most important word]] in French is the word for the afternoon snack.  In IIT
Kharagpur's Nehru Hall, there were no such pretensions about food; but a strange reverence was shown
to the place where food was often eaten, the mess hall. The single most important phrase in this
hallowed ground was "Excuse Me", the over-used English phrase most often heard in Victorian dramas
when heroines flustered by their love interest utter these words and an escape hatch is opened to
them. Second-years were implored: when you are done eating your food and are stepping away from the
table, you /must/ cast this magical incantation. Once cast, the spell worked wonders as it
suppressed the bout of shouting and mocking from third-, fourth- and fifth-years. Curiously,
everyone in the third-year and above inside the same dining hall was exempt from this /rule/. As in
Pride and Prejudice, another Victorian-era drama, the female characters who are being married off
have little say in whom they are married to, while the men have all the choice that they could
possibly want; so in Nehru Hall, second years had to follow a lot of rules designed to keep them
"humble and respectful", while everyone else lead rule-free lives. *This* dichotomy was a part of
hazing at IIT Kharagpur, affectionately referred to by the euphemism, "Orientation Program", or
simply, O.P. I recount my experience of O.P. in this 4-part series. This is the third part,
Victorian-era Dining Hall Etiquette.

#+begin_export html
<!--more-->
#+end_export

Closely following the sermon on [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/11/orientation-program-iit-kharagpur-part-2/][self-introduction]], everyone in the hostel appeared to be dead-set on
driving arguably outdated customs and practices into the brains of second years. As their location,
they chose the one place that second-years were bound to visit a few times each day: the dining hall
(or mess hall or just, "mess"). The food that was served here was edible; I hesitate to add any
other epithet. While eating this food required a profound acceptance of the status quo, the
experience of second-year students in particular was improved by third-, fourth- and fifth-years
engaging the hungry masses in spirited conversations about rules, the importance of rules, and
adhering to rules. They also provided comic relief, by making jokes at the second-years'
expense. Laughing at a joke someone else makes at your expense is the age-old path to stress-relief.

The topics of discussion ranged from the slightly uncomfortable[fn:2] to the deeply
distressing[fn:3]. And like the proverbial lunch lady in kindergarten, the tormentors pointed out
the slightest violation in etiquette among the victims.

Did you leave the table without excusing yourself? This would earn you an inexplicably long lecture
about values, respect for elders and propriety. The lecture did run the risk of provoking a victim
into an impassioned speech about the propriety of tormenting ostensible strangers at the dinner
table. The victim might ask the third-years "What gives you [[https://youtu.be/gk9C1ukV-EM?t=19][the right]]?" I did not witness any such
altercation though, and it was probably because /all/ second years held these people in /high/
regard.

Did you step away from the table to get food at the buffet but did not put your chair in a position
indicating that it was occupied? This minor transgression of a deranged directive would be the
trigger for an unsolicited meditation on the meaning of "rules" and the importance of following them
when you are in your second year and disregarding them when you are in your third year[fn:1].
Apparently, rules should be followed at least for a year, so that one gets a /taste/ for what
rule-following /feels/ like. After that, the former rule-followers are promoted to be "enforcers". I
live by this even today and never follow any rule for more than a year; it has served me well in the
real world.

Did you have the /audacity/ to walk into the mess-hall in attire that exposed your bare knees?
Well, this was the cardinal sin and would provoke a collective gasp in the form of a loud,
screeching, and wholly unpleasant noise emanating from the exalted fourth-years. You would be gently
reminded that the rules prohibited this *kind of attire*. Some second-years might be dispatched to
the back of the dining hall, to read the list of rules and give the fourth years a summary of what
was written there. Others might face the less loaded question, "Can you even read English?". To this
question, I present the answer that I prepared but never had a chance to deliver: "Yes, I can read
English. Also, I am particularly glad that I can write English; for I intend to return to my room
and write down what just transpired in a note for reference in the /future/."

These conversations might appear normal or even friendly. Some might counsel the victim, "This kind
of rhetorical questioning is how barbarians have broken ice for centuries. Cheer up!". Yet others
might console, "This was nothing compared to what happened in the dining halls in my college hostel
...". These people are *right*! I find the latter piece of nostalgic recounting particularly
soothing. The world is famously resistant to change. What happened to your parents in college *must*
happen to you in college. It will also happen to your offspring. Why else would the most memorable
phrase about /change/ be *"/the lack of/ change is the only constant"*?

Some second-years managed to avoid the tables where these vultures scavenged for their almost-dead
prey. Others employed devious methods and avoided these conversations altogether during the
prolonged period of a month. These conversations in the mess could jump out of the dark and assault
anyone, those who were complacent and had dropped their guard were particularly
susceptible. Everyone knew that this was going on in the dining hall as they heard stories from
second-year students who praised their seniors in curiously crude language. The anxiety felt by the
/about-to-be-hazed/ is identical in scale to the exhilaration felt by the /already-hazed/. At least
the /already-hazed/ can rest easy knowing that they have gained access to /knowledge/ that is
refused to people who have the misfortune of living in civil society!

To the diligent conductors of O.P., one second-year student left uneducated equaled defeat; "No man
left uneducated", was their creed. So, they took the fight to educate to the room in which these
second-years slept after a long day. In the final installment of this 4-part series, I will relate
the curious nights during which second-years stood in neat rows on the ground in the middle of the
night, while fifth-years and even some alumni discoursed at them from the first-floor balcony.

-----

*Programming note:* This is the third part of a 4-part series.

| Post                                                  | Date           |
|-------------------------------------------------------+----------------|
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/10/orientation-program-iit-kharagpur-part-1/][The Curious Case of the Dweller Who Wouldn't Move Out]] | 10th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/11/orientation-program-iit-kharagpur-part-2/][The Sermon in the Common Room]]                         | 11th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/12/orientation-program-iit-kharagpur-part-3/][Victorian-era Dining Hall Etiquette]]                   | 12th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/13/orientation-program-iit-kharagpur-part-4/][The Midnight Assemblies]]                               | 13th May, 2021 |

-----

[fn:1] A second-year student /not following/ the rule book and a third-year student /following/ the
rule book were both subject to ridicule.

[fn:2] "I don't care about this at all"

[fn:3] "What is he talking about and when will he stop?"
