#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Notes and Review - A Burning (Majumdar)
categories: book-review india poverty
---
#+end_export

A Burning is ostensibly about 3 people. Their lives are entwined in rather banal ways: teacher, a
former student, a young woman helping a slum dweller learn English, a transgender beggar who is
learning acting, an acting teacher who has never had a real audience. Their hopes and dreams are
conventional: The young woman gets into a good school and manages to escape her past and moves
solidly into the middle class. The slum dweller hopes to learn acting and make it big in the movie
industry. Under this shroud of normalcy, and sometimes using it as a tool, Majumdar captures the
depressing nature of the life they lead. And these characters stand-in for a whole group of people;
the group that has missed the social mobility bus; the bus was packed in the 1970s with first-time
engineers and doctors and lies overturned on the side of the highway today.

#+begin_export html
<!--more-->
#+end_export

I lived for 5 years in West Bengal during college. The college was situated inside an insulated
cocoon where the outside world rarely interfered. Every time I went to Kolkata, I had to go through
Howrah Station. This railway station has been around since colonial times and it has remained mostly
unchanged during that time. The abject poverty that is prevalent in the state and the stark income
inequalities which are prevalent across India crystallized into a solid object which I had to
wrestle with, every time I went through the railway station on my way to a waiting Uber
driver. Majumdar has captured all of this terribly well.

For all the astute observations about poverty as a way of life, and the irrational character of
social mobility, this novel is surprisingly dispassionate. The chapters titled "Interlude" are
testament to this feature: The stories inside these chapters are the most touching renderings of
poverty I have ever read. In particular, the story in which 2 young men are demanded to pay an
exorbitant entry fee to enter a mall, a fee that seemingly does not apply to plump women who look
rich, has remained in my mind ever since I read it.

#+begin_quote
So Raju and I stepped away from the entrance. We looked at each other. Neither of us wanted to say
it. So Raju clapped my back and I smacked his shoulder, and we went to the syrup-ice stall and had
some orange syrup-ice. Then we went back to work. Him to his house painting, that paint-smelling
turban on his head again. Me to my electrician's shop. It was giving me pain in my wrist, pain in my
thumb. At least the syrup-ice was delicious.
#+end_quote

/This/ is the shadow of discrimination that inequality inevitably creates. While many of my
middle-class and upper-middle-class acquaintances strongly believe that India has come a long way
from the days of unemployment and poverty in the late 20th century, the improvements have been
captured by a few segments. There has been limited society-wide improvement in the decades since.

All three characters have an arc of social mobility. This arc is defined by the sacrifice that they
have to make. In the case of the soon-to-be politician, it is the witnessing of a mob lynching,
fueled /only/ by communal hatred. In the case of the soon-to-be actor, it is the abandonment of a
benefactor and friend. The main character sacrifices her life to "answer" the demands of the public,
that blame be placed upon /someone./

#+begin_quote
[In the courtroom, the judge announced his ruling,] "And, on the other hand, we have the word of a
hijra[fn:1], an individual who begs on the streets for money, saying the defendant taught her
English. Be that as it may"--the judge takes a deep breath, ... --"it is clear that the defendant
has long been disloyal to the values of this nation. The defendant has spoken clearly against the
government, against the police, on the Internet, on Facebook dot-com. This lack of loyalty is not
something to be taken lightly. It is its own strong piece of evidence. There is a case to be made,
as well, for soothing the conscience of the city, of the country. The people demand justice." He
goes on.
#+end_quote

These sacrifices are irrational. Towards the end of the book, that last sacrifice made by the
protagonist enraged me. How can one person be sacrificed at the altar to pacify the demands of a
nation for justice? Yet, what right do I have to be enraged? The first decade of the 21st century in
India was ridden with terrorist attacks across the country. After each attack, security was
increased and people (sometimes, communities) were sacrificed. The nature of these sacrifices is the
same and if I am enraged by the fictional one, then I *must* battle with the injustice inherent in
the non-fictional ones too.

The final notable feature of the novel is that the main incident in the novel, the burning of the
train, takes up so little of the story. It is described. And the main character's feelings about it
and where she was in relation to the attack are also described. But we never get to see the damage
that it has done. Our perspective is forcefully limited to the daily lives of the 3 main
characters. Unfortunately, it includes such useless sources such as the nightly shows that PT Sir
watches on his TV or what Lovely's friends tell her about their opinions. In this, I think that the
author has pointed towards the horrifying nature of life in a world of information abundance: *What
has happened /might/ be important. What others are saying about it is /always/ more important.*

As tragedies engulf countries around the world in the form of inflation, food insecurity, heat
waves, and war, there is a sense that this is business-as-usual. Today's tragedy is the latest of a
series of vignettes; certain to fade away when the next one appears.

-----

*P.S.* One nice part of the novel that I appreciated was that one of the characters who is in the
process of learning English, speaks in broken English throughout: (even in her inner monologues)

#+begin_quote
Even a dog which is looking like a wolf is enjoying the ride in AC comfort. All of them are ignoring
me. The public is wanting blood. The media is wanting death. All around me, that is what people are
saying.
#+end_quote

This character, Lovely, is learning English and she makes the kind of mistakes that are
characteristic of a beginner in India, prominently, the usage of the continuous tense everywhere.

[fn:1] The Hindi word for transgender.
