#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: What To Do With All This Media Theory?
categories: media rant
---
#+end_export

There has been a lot of media theory talk over the past year in the mainstream (newspapers, news
websites, television) and on the intellectual sidelines (podcasts and blogs). The discourse is heavy
on the origins and consequences of the continuing, effectively unstoppable, decay of communication
over traditional media. (Savvy authors might use terms like "signal to noise ratio.") However, all
this discourse is suspiciously devoid of any advice for us, the spectators. Repeatedly, there is the
defeatist assertion that most people will /probably/ be addicted to their screens despite knowing
how the screens manipulate them. I don't think this defeatism is necessary. What should people do to
avoid the consequences that authors are expounding on? Should they try to cut their information
intake? Should they go "off the grid," a concept that Opinion writers have made a cottage industry
out of talking about?[fn:5] The discourse has no response. Here's my non-defeatist take.

#+begin_export html
<!--more-->
#+end_export

* A Rant

The premise of this whole post is that current media theory doesn't offer solutions or even
lighthearted pointers towards a better way to use our tools and consume media. In fact, the most one
can *probably* get from it is that we are in a transition period and we shouldn't worry because
everything will get sorted out, by someone, somehow, at some vague point in the future. That advice
is not good enough. My belief is that theory and discourse should not merely theorize about reality;
it should put forth recommendations for readers about the methods for applying realizations in
real-life. And the action has to happen *now.*

Before presenting the defeatist examples, let me say outright that the people giving the defeatist
takes are the most informed on the subjects and I respect their work, because I have learn most of
what I know from their work. Disclaimer aside, a couple examples of the defeatist takes from people
who talk about media:

#+begin_quote
a lot of us, most of us, maybe are going to and do spend a lot of time staring at a screen, skimming
with distractions everywhere

-- [[https://www.nytimes.com/2022/11/22/opinion/transcript-ezra-klein-interviews-maryanne-wolf.html][Opinion - Transcript: Ezra Klein Interviews Maryanne Wolf - The New York Times]]
#+end_quote

#+begin_quote
As I began reading the novel I’m now close to finishing, it was difficult for me to get lost in the
story. When I do read something that is intellectually demanding, I find my mind wandering from the
page after only a few moments. I assume that by now this is just how most people feel about reading
and that some may not even know that there is any other way.

-- [[https://theconvivialsociety.substack.com/p/reading-as-counter-practice?publication_id=6980&post_id=87673987&isFreemail=true][Reading As Counter-Practice - by L. M. Sacasas]]
#+end_quote

#+begin_quote
If the internet is as transformative a technology as the printing press, and I think it's certainly
comparable, then it's going to take several decades to fully adjust to the changes it has wrought.

-- [[https://www.nytimes.com/2022/07/26/podcasts/transcript-ezra-klein-interviews-sean-illing.html][Transcript: Ezra Klein Interviews Sean Illing - The New York Times]]
#+end_quote

I started writing this post after [[https://www.nytimes.com/2022/11/22/opinion/ezra-klein-podcast-maryanne-wolf.html][listening]] to Maryanne Wolf on The Ezra Klein Show. Wolf is
eloquent throughout the show, and she spoke with the zeal and enthusiasm of a real ideologue. She
really believes in her work, and her work was magnificently revealing about the ways our reading
habits on screens and on paper are intertwined with each other. As I mentioned above, the ways in
which parents' addiction to screens affects children is another part of the conversation where her
expertise shines through and she articulates things with amazing clarity.

Towards the end of the show, the host asks her a simple question: "What should someone who /wants/
to become a deep reader do to regain the mythical state of deep reading that Wolf advocates for?"
Here, Wolf falters. First, she shares her habit of spending 20 minutes after waking up and before
going to sleep reading a book, philosophy in the morning and classics at night. The host pushes back
on her suggestion. Then, she suggests that it is up to each individual. Then, she digresses from the
topic of reading to the phenomenally more complex topic of "just being yourself" using other mediums
such as music. This was a disappointing end to a great conversation.

L. M. Sacasas' newsletter is rich in media theory but light on recommendations, and perhaps it is so
by design. Illing's conversation about their new book about the connection between media and
democracy was also informative: It touches back to the origins of media theory during the post-war
period, when the TV was initially introduced. Illing is optimistic about the tools we have today but
thinks that we are only at the beginning and that we don't need to really worry too much about the
bad ways in which these tools are affecting us, because a lot of change is yet to come.

The lack of recommendations might also be from the structure of these conversations and the medium
through which they reach their audience: The News. The self-inflicted wound of saying consume less
news on a newspaper is not beyond any of these experts; however, I doubt that they would say it. The
closest I can think of is something that Ezra Klein said in his podcast with Johann Hari about
attention, in which he says that we should consume far less news than we do.

* The Constants

Here are the constants. These are the things that are referred to as "required reading" in most of
the conversations, and are rarely debated as being true.[fn:6]

1. Medium is the Message
   1. McLuhan wrote a book about this: "Everything on T.V. should be entertaining. Education shows
      like [[https://www.imdb.com/title/tt0063951/?ref_=ttls_li_tt][Sesame Street]] are on T.V. Kids who watch TV end up believing that education should be
      entertaining too." It's not that they don't learn something on these "edutainment" shows; they
      /do/ learn something useful and this complicates things furthers, because they now expect that
      education should be presented to them in an entertaining manner. (Remember all the "Let's make
      Mathematics fun" talk? Duolingo tries to make language learning fun by gamifying it.)
2. Attention should be conceptualized as a resource. Attention spans are decreasing.
   1. Attention span is (roughly) the period of time for which someone can pay undivided attention to
      a single concept or thought. Attention as a resource is a way of conceptualizing what is being
      sold by Facebook to the advertiser, when they provide the Newsfeed for free.  There is no
      monetary exchange. The only exchange is temporal and so time itself (or attention, the act of
      spending time on something) is the resource.
3. Reading is in decline
	#+begin_quote
	The percentage of 12th graders who read a book or a magazine every day declined from 60% in the
	late 1970s to 16% by 2016, and 8th graders spent almost an hour less time watching TV in 2016
	compared with the early 1990s

	-- [[https://psycnet.apa.org/doiLanding?doi=10.1037%2Fppm0000203][Trends in U.S. Adolescents' media use, 1976-2016: The rise of digital media, the decline of TV, and the (near) demise of print. - PsycNET]]
	#+end_quote
4. Mass media is designed around consumer buying. Sensational coverage gets people more engaged
   1. This has been a known trope about television coverage of terrorism, protests and accidents, or
      other traumatic events for a while now. Every protest produces the same set of photographs: A
      group of people, preferably in masks, throwing dangerous objects like rocks and Molotov
      cocktails at armed police officers, preferably in riot gear. All of it is because of the
      economic absurdity of covering something without sensationalism. This [[https://www.youtube.com/watch?v=srnA3cNTsXQ][video]] illustrates this
      point.
5. Content is designed to be engaging and sensational, not informative or educational
   1. I wrote [[http://localhost:4000/2021/03/14/unscientific-comparison-of-news-websites-2-objective-analysis][a series]] of posts analyzing the home pages of several news websites at the same point
      in time. The [[https://www.youtube.com/watch?v=ugjCCWdKr8Y][Nancy Grace section]] in the TV show Newsroom is indicative of this tendency.
6. Information is super-abundant on the Internet. Algorithms sort through this information and act
   as the middlemen who deal content to users.
   1. Long gone are the concepts of a trusted TV stations or a single newspaper of record. There are
      innumerable sources of information on the internet and anything you want to believe can be
      proved by picking the sources that support your viewpoint and smearing those that oppose your
      beliefs
7. Algorithms are designed to increase engagement and profits through advertising networks
   1. Many news websites have advertising through ad networks, or pleas for donations on all of
      their articles. Clearly, "journalism" is not paying for itself.
8. Some people /hack/[fn:1] the media by being egregiously engaging and sensational
   1. Trump, Musk, Kangana Ranaut
9. Twitter is *not* the platform for informed discourse
   1. Saunders, who wrote the [[https://www.nytimes.com/2022/11/08/opinion/ezra-klein-podcast-george-saunders.html?][Braindead Megaphone]], says that Twitter is a strange place because it
      places a limit on what can be said and how many characters can be used. Why is this limit
      being placed? See "(1): Medium is the Message." What can be said in 280 characters is probably
      neither useful nor insightful; it is merely provocative. (Typical example of click bait that
      is now accepted: "Why did Elon Musk buy Twitter? A thread. 1/n")
10. Twitter *is* the platform for informed discourse
	1. Ezra Klein has said on his podcast repeatedly that Twitter is an important place for
       journalists because that is where they get their story ideas and that is where they realize
       what the "vibe" of a particular subject really is. Clearly, most journalists think that
       Twitter is a good platform, despite vehemently denying its validity and arguing about the
       ease of being manipulated into believing something is more important than it actually is.
11. Movement and vivid colors capture people's attention
	1. This is a dig at some of the more obvious takes around parenting. Children don't come into
       possession of video games / gaming consoles / digital screens in a vacuum. Parents buy these
       things for their children to achieve some goal. This goal might very well be to fan the
       parents' addiction to media and screens, an addiction that is not good for either parent or
       child. Wolf's expertise with children, literacy, and the effects digital skimming culture
       have on parents and children is another very good part of [[https://www.nytimes.com/2022/11/22/opinion/ezra-klein-podcast-maryanne-wolf.html][the conversation]].

* The Actions

Here are the actions that I took over the past few months.[fn:2]

** Less Skimming. Less News.

#+begin_quote
Stop reading the news. You don't need to know *everything.*
#+end_quote

Okay. I am going to rip the band-aid off real quick: *90% of News is either sensationalist or
useless.*[fn:3]

I used to be a big-time news reader. I read a morning briefing from the New York Times.  I listened
to about 40 minutes of news podcast on an average day.  I spent a big portion of free time during
the day reading articles that appeared in the notifications on my phone. The constant flow of news
powers the adrenaline rush of being part of a (hyper) connected world. However, it has no practical
use. I don't work in the news or any news-adjacent business, and I have no obligation to be informed
of "current affairs."

Now, I listen to 20 minutes of news, from a briefing podcast, every morning. This has been my only
source for the past 6 months and I am doing just fine. I will not be returning to reading more news
anytime soon.

*A caveat:* I am yet to completely think through the impact this has on my beliefs about democracy
itself: I have said before on this blog that an informed electorate is a prerequisite for a
democracy that works. I look forward to reading Illing et al's work about democracy and media
consumption and trying to have clearer thoughts on the subject.

** More Magazines

#+begin_quote
Buy the print version of a non-news, non-"current affairs" magazine
#+end_quote

I used to be completely disconnected from magazines. I did not appreciate the form until last year,
when I subscribed to [[http://localhost:4000/2021/01/12/the-new-yorker-subscription][the New Yorker]] on a whim. While that particular magazine published at a rate
that was much too fast for me (4 issues / month), I subscribed to the print version of WIRED, a
tech- and media-adjacent magazine this year (1 issue / month). I really like the format: The shorter
columns are great for free time during the day, the longer reads are thought-provoking profiles or
excerpts from books.  There is almost no politics in the whole magazine. Topics are not limited to
current affairs. (My favorite long pieces from the last few issues was [[https://www.wired.com/story/multifarious-multiplexity-taika-waititi/][an eccentric profile]] of the
filmmaker Taika Waititi and [[https://www.wired.com/story/david-wengrow-dawn-of-everything/][a fascinating interview]] with one of the authors of the book The Dawn of
Everything[fn:7].)

*A note:* Magazine aggregators like the Apple News service might look inexpensive.  I suspect that
having access to *that* much information can tempt readers to switch back to the digital skimming
modes of reading. So, for now, I am staying away from aggregators and algorithms.

** More Fiction

#+begin_quote
Good fiction is a great story with interesting people in it.
#+end_quote

I think fiction is where the most amazing type of reading happens. Regrettably, a lot of non-fiction
is little more than information gathering or propaganda for some hustle culture concept like Todo
lists or habit forming or how CEOs spend their day.  Only the absolute best non-fiction books[fn:8]
rise above the "merely communicating information" level to the "mindset forming" level.

*A note:* A lot of non-fiction, especially the "top of the best seller lists" non-fiction books, are
little more than a single, interesting insight repeated over the entirety of a 200-page light read:
These are the /airport best sellers/ that you should stay away from. [[https://twitter.com/IfBooksPod][This podcast]] pokes fun at these
books and is entertaining.

** More Blocks of Time

#+begin_quote
Reading for 2 hours at a time is better than for several periods of a few minutes each
#+end_quote

This was my most useful insight of the past year. Deep reading (or the focus required for that)
doesn't just happen. It is also very hard to maintain that focus consciously. So, the best method to
naturally prepare yourself for a period of deep focus is to set aside a large block of time and do
nothing except read in that block. This is hard, and perhaps many weeks will go by until I
get a satisfying block to do this. Nevertheless, I have resorted to this approach now.

-----

For something as open-ended as reading, the levels of motivation vary over time and the books that
you pick up; chances are high that you can turn your "desire" to read into a "habit" of reading
through any sort of strict framework. Coming up with the framework and enforcing it on yourself
though? Well, *that* is on you, the reader. The hardest part of doing more "deep reading" is that
there is no trick. But that should not prevent media theorists from putting forth better
recommendations.

* Footnotes

[fn:8] In my opinion: Mokyr's [[https://www.goodreads.com/book/show/257489.The_Lever_of_Riches?from_search=true&from_srp=true&qid=0TUIxmJBDw&rank=1][book about technological progress]]; Rosling's [[https://www.goodreads.com/book/show/34890015-factfulness?from_search=true&from_srp=true&qid=KbplT0SRmi&rank=1][book
about the world getting better]]; Piketty's [[https://www.goodreads.com/book/show/25547614-the-economics-of-inequality?from_search=true&from_srp=true&qid=7MO2NH9yCc&rank=1][book]] explaining how economic inequality should be measured

[fn:7] The interview might be fascinating for this single line: "Wengrow had no contact with Musk,
about whom he appeared to know little, and care less."

[fn:6] For some of the constants I have added some notes in the list about where the concept comes
from and how I understood it. These notes are completely optional and you can skip them if the
constant is self-evident or obvious to you.

[fn:5] "I went into the mountains for a week. I was completely off the grid. There, I had the
amazingly original insight that we are addicted to our phones."

[fn:4] The tool Beeminder does just this, with real money.

[fn:2] My reading about media and media theory is only beginning. I hope to revisit Postman's book
about television, the recent book by Illing and co. about the connection between government and
media, and a few research papers that Wolf mentions in her conversation.

[fn:3] There is a syntactical fight about what "useful" really is and who gets to decide it. In this
case, I get to decide it because I found that most of what I was reading in the news was not useful
except as trivia.

[fn:1] i.e. manipulate. The media people are vehement that they are being manipulated.
