#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Thoughts About The Beatles Documentary
categories: music beatles
---
#+end_export

I found out about the Beatles documentary from a [[https://www.thisamericanlife.org/756/but-i-did-everything-right][podcast episode]]. The host was talking about [[https://www.youtube.com/watch?v=07q95KiVguc][a clip]]
showing the Beatles legend, Paul McCartney, composing the song "Get Back." The stunning part of this
video was that he had started from nothing. He was idly strumming chords on his guitar, early in the
morning. Ringo Starr and George Harrison were sitting across from him; they appeared disheveled,
tired, and sleepy. The final Beatle, John Lennon, was nowhere to be seen. I watched this video a few
times; hoping to get a glimpse of something around McCartney which gave him the inspiration to come
up with the melody. I wonder if other viewers were watching the video looking for a similar kind of
revelation. But there was nothing. McCartney had created the song out of nothing; like a vaguely
remembered dream converted into a beautiful melody. I learned more about what the documentary was
and where the footage had come from. (Admittedly, I went through this information gathering process
in a frenzy.) This past week, some theater chains in Japan capitalized on the mania of Beatles fans
by airing a 1-hour special, *The Rooftop Concert*, for a limited period of time. I watched the
special, and here are some thoughts about my experience.

#+begin_export html
<!--more-->
#+end_export

Watching the special was a jarring experience: *It shows London in the late 1960s in
high-definition, color video.*

Until now, all of the footage I have seen from before 1990 has been grainy and monochrome. Color
movies have been around since the 1940s; but I had not seen any documentary which was shot in color
*and* high resolution until now. The reason I attributed for this is that all of the media that we
consume from the 20th century was recorded off a TV screen, possibly originally recorded on tape
using the VCR and later digitized. The resolution supported by satellite TV sets back then was much
lower than our modern standards of "High-Definition." So, the only way to get higher quality footage
would be to go back to the original tapes with raw footage; digitize those tapes; re-edit the
documentary in the same manner; and release the HD digital version of the same documentary. It does
not make much economic sense to do this for most documentaries.

For the first couple minutes, we see footage from around London. I was tempted to believe that this
was a period movie. This temptation is strong almost throughout the hour-long performance. It is
especially strong when either spectators or the view on the street is shown. On the street, people
are shown standing around during their lunch hour and listening to the performance on the roof of a
building on Savile Row, the street on which the Beatles had a studio where they recorded their
albums.

I was so used to seeing the Beatles perform through videos on YouTube that the scenes which included
them were the most comforting of the bunch. They perform 6-7 songs on the roof of their
building. There is much drama surrounding three police officers who are trying to get them to turn
down the racket, owing to noise complaints from other residents and businesses in the
vicinity. There are some "taking the crowd's temperature" interviews happening on the
street. Questions are posed to the spectators who are standing around listening.

The hour-long special used IMAX technology, which meant a larger than normal screen and particularly
sharp, surround-sound audio. This made the whole experience a lot of fun. I had resigned myself to
being able to listen to bands from the 20th century /only/ on domestic audio equipment. The full
version of this documentary, about 8 hours long, has already been released on Disney+ (or [[https://www.hotstar.com/id/tv/the-beatles-get-back/1260073692][Hotstar]],
if you are in India). So, I caught myself thinking about whether it was worth going to the theater
to watch something that was already available to me online, on demand.  However, just as quickly, I
realized that I was comparing two completely different experiences.  (Irrespective of how good or
bad a movie is, I have never regretted watching it in the theater. So, your mileage might vary.)

I was taken aback by how /familiar/ London looked. I have never been there myself, and all my prior
knowledge of it has been through either news footage or TV shows set in Britain. Particularly
familiar was the attire of everyone on the street. Even the cars that were on the street and mundane
details like the glasses that people were wearing: Everything just seemed /familiar/ and /period/
appropriate.

I could not explain this familiarity, or my heightened sensitivity to it, because my understanding
was that fashion has changed significantly since the 1960s. One possible explanation is that our
expectations of each period have been conditioned by frighteningly *accurate* portrayals. This
conditioning has made /real/ historical footage neither surprising nor disorienting, as they simply
serve to confirm one's prior expectations of the period being depicted.

The questions on the streets brought out a very interesting phenomenon, to whose existence I had not
paid the requisite attention. The Beatles were not universally liked. They were very popular, but
many people thought that their music was too similar to /pop music/; too simple; [[https://www.youtube.com/watch?v=In6gCrGeZfA]["very indulgent,"
as Bob Dylan]] quipped. Liking the Beatles was a /slightly/ rebellious act in the 60s, I presume. Only
slightly because their lyrics were wholesome and there was little of disrepute or [[https://www.youtube.com/watch?v=v9gLmBgUTV4]["Satanic
influence"]] there that someone could reasonably complain about. Indeed, two adults say that they have
not heard the Beatles themselves, but that their children buy their records. Liking pop music,
ironically, is always frowned upon by /someone./ There were two elderly people who were unhappy
about the racket. One of them complains about having been woken up from her sleep. That, I thought,
was a funny touch.

The drama with the policemen leaves one feeling conflicted. They were doing their job in trying to
stop the performance. When the policemen reach the roof and are standing behind the band, /as/ the
band is performing, McCartney turns back and looks at them multiple times. His demeanor clearly
shifts after the first time he looks back and notices that the police are trying to shut them
down. This renewed perception of the performance as an act of rebellion seems to energize him. He
starts smiling, and is clearly willing to taunt and defy the policemen, should it come to that. As
their last song, Get Back, comes to an end, he adds a few impromptu lines about how the police don't
like them performing on the roof and might even arrest them for it.

I have one final thought about the 1-hour special: The questions that were asked on the street were
/cringe worthy./ The conversation always seems to run something like this:

- *Question:* Do you know what you are hearing?
- *Answer:* It is the Beatles, right?
- *Question:* Yes. Do you like it? / Would you buy their records?
- *Answer:* Yes, absolutely. I love them!

Or, like this (probably worse):

- *Question:* Do you know what you are hearing?
- *Answer:* No
- *Question:* It is the Beatles
- *Answer:* Oh, okay
- *Question:* Do you like the Beatles? / Would you buy their records?
- *Answer:* Sure, I will try it out

Every time the interviewer said "The Beatles," I cringed. I think that this idea to ask people on
the street about the performance was the documentary producers'. Perhaps, they wanted to show that
the band was well-liked, and that this stunt would pay-off big time. However, for a band as popular
and well-known in the 1960s as them, I thought that it was superfluous to repeat this conversation
several times and get people to approve of their music. At times, it felt like pandering to a future
audience; an indirect way of saying "The Beatles were a big deal back then. We knew that. You should
know that too, viewer in the future." I did not get any kind of wholesome message. The producers
could have been secure in the Beatles' position as a genre-changing musical force.
