#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: A Chronicle of Predominant Conversations (2023)
categories: technology summary
---
#+end_export

A large number of articles, opinion pieces, blog posts, video essays, podcasts, television dramas,
and movies saturate the information landscape. It is bad form to say that there is more out there
than can be read by any one person. The dreaded information overload has arrived. A few acknowledge
the existence of this swarm of multimedia. The majority beckon an Algorithm, entrusting it with the
responsibility of collecting, filtering, and sorting them in the unknowable order that each
component particle of the majority expects. Opting out is futile. Not knowing about something is
superior to not knowing about its /occurrence./ What follows is a view of culture and society based
on the contents of 3 issues of the WIRED magazine.

#+begin_export html
<!--more-->
#+end_export

Suggestions of openness are reduced to the realities of great coffee in the lobby in less than a
decade.

#+begin_quote
Yet OpenAI /has/ changed. The nonprofit board might technically be in charge, but virtually everyone
in the company is on the for-profit ledger. ... It's got product managers and engineers working
constantly on updates to its products, and every couple of weeks it seems to ping reporters with
demonstrations--just like other product-oriented Big Tech companies. I have visited virtually every
major tech company in Silicon Valley and beyond, and not one surpasses the coffee options in the
lobby of OpenAI's headquarters in San Francisco.

Not to mention: It's obvious that the "openness" embodied in the company's name has shifted from the
radical transparency suggested at launch.

-- [[https://www.wired.com/story/what-openai-really-wants/][What OpenAI Really Wants | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:43])

#+end_quote

Product companies have a bright future, if they focus on engagement.

#+begin_quote
Roblox Connect, then, is an attempt to get people to just ... hang out in Roblox, even when they're
not gaming. Hanging out equals more engaged minutes; more engaged minutes leads to better
advertising opportunities and "bookings," the purchase of virtual goods using Roblox's digital
currency, Robux.

-- [[https://www.wired.com/story/soon-youll-be-zooming-in-roblox/][Soon You'll Be Zooming in Roblox | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:24])

#+end_quote

... and if that engagement is tied to /commercial information/.

#+begin_quote
First of all, in search, people come looking for information. Over the past many years, you know,
how we present that has dramatically evolved. But we are still trying to help people find the best
information that exists online. Inherently, people are also looking for commercial information, and
ads are very valuable commercial information, because they connect merchants and businesses, small
and big, to users. None of that changes just because we are applying AI deeply. When we evolve
search with generative AI, we'll apply the same principles. It's important to us to connect users
with what's out on the web, and we are working deeply to make sure that continues to work
well. ... We want to make sure users are consuming those sites. So I don't think the core part of
the experience will change. We will have a space for ads in a way that makes sense for users and
particularly on commercial queries

-- [[https://www.wired.com/story/sundar-pichai-google-ai-microsoft-openai/][Sundar Pichai on Google’s AI, Microsoft’s AI, OpenAI, and … Did We Mention AI? | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:44])

#+end_quote

Creation myths allow protagonists to enter closed restaurants and make small talk with staff after
they were /dropped off/.

#+begin_quote
I arrived at a restaurant to meet Moore and tugged at the door. Locked--it was one minute before
opening. ... When the hostess let me in, I gave her the reservation name. "The other guest is
already seated," she said. ... That was impossible. The restaurant wasn't open yet. ... "She's been
here awhile," she explained. ... She'd been dropped off earlier and passed the time by making
conversation with the staff.

-- [[https://www.wired.com/story/patricia-moore-sacrificed-youth-to-get-tech-bros-to-grow-up/][She Sacrificed Her Youth to Get the Tech Bros to Grow Up | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:10])

#+end_quote

Definitions are changing.

#+begin_quote
I am a good mother. I define motherhood in much broader terms than just giving birth."

-- [[https://www.wired.com/story/patricia-moore-sacrificed-youth-to-get-tech-bros-to-grow-up/][She Sacrificed Her Youth to Get the Tech Bros to Grow Up | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:40])

#+end_quote

Podcast-ready essays read by AI-generated voices.

#+begin_quote
The 19-year-old speaks in the confident, podcast-ready tone of a Silicon Valley entrepreneur who
sees the world in terms of problems to be solved, ending every other sentence with, "Right?"
Listening to him wax on about defensible moats and the "S-curve" of societal growth, it's easy to
forget he can't legally drink. But then, occasionally, he'll say something that reveals the
wide-eyed undergrad, open to the world and still figuring out his place in it. Like the time he and
a friend walked around the Santa Monica pier until 3 am, "talking about what we value." Semrai
thinks a lot about how to find balance and happiness. "I think, while I'm young, it probably lies
more in exploring the derivative," he says, "chasing the highs and lows."

-- [[https://www.wired.com/story/ai-detection-chat-gpt-college-students/#intcid=_wired-bottom-recirc-v2_00a3c20c-d127-4a82-9216-e7c393a9984e_wired-content-attribution-evergreen][The AI Detection Arms Race Is On | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:41])

#+end_quote

Profit still matters.

#+begin_quote
For a staunch advocate of the private sector, L also let slip flashes of exasperation at how
/corporate/ corporations can be. ... Being on the same side of a war, it turned out, was no
assurance at all of being in sync.

-- [[https://www.wired.com/story/ukraine-russia-war-military-retail/][In the War Against Russia, Some Ukrainians Carry AK-47s. Andrey Liscovich Carries a Shopping List | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:03])

#+end_quote

The masters spoke. They said, "AGI is not on the way." No one was listening.

#+begin_quote
Now, Microsoft has an exclusive license to commercialize OpenAI's tech. And OpenAI also has
committed to use Microsoft's cloud exclusively. In other words, without even taking its cut of
OpenAI's profits (reportedly Microsoft gets 75 percent until its investment is paid back), Microsoft
gets to lock in one of the world's most desirable new customers for its Azure web services. With
those rewards in sight, Microsoft wasn't even bothered by the clause that demands reconsideration if
OpenAI achieves general artificial intelligence, whatever that is. "At that point," [[https://www.wired.com/story/microsofts-satya-nadella-is-betting-everything-on-ai/][says Nadella,]]
"all bets are off." It might be the last invention of humanity, he notes, so we might have bigger
issues to consider once machines are smarter than we are.

-- [[https://www.wired.com/story/what-openai-really-wants/][What OpenAI Really Wants | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:55])
#+end_quote

The optimists have abandoned ship.

#+begin_quote
"Artificial intelligence, cloning, genetic engineering, [[https://www.wired.com/tag/vr/][virtual reality]], [[https://www.wired.com/tag/robots/][robots]], nanotechnology,
bio-hacking, space colonization, and autonomous machines are all likely coming, one way or
another. But we must take a stand and insist that human values are folded into the development of
each and every one of them." Only a few years later, here he is rejecting not just these
technologies, but technology writ large as a solution to our problems.

-- [[https://www.wired.com/story/doug-rushkoff-survival-of-the-richest/][Doug Rushkoff Is Ready to Renounce the Digital Revolution | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:35])

#+end_quote

Humans communicate to win esoteric games that simulate a world without bureaucracy.

#+begin_quote
This is the current Diplomacy metagame. Game theory calculations undergird most utterances, and even
humans communicate in code. Lerer joked that in modern-day online Diplomacy, even human players
wouldn't pass the Turing test. Before Cicero, it seems, humans had already started playing like
AIs. Perhaps, for an AI to win at Diplomacy, Diplomacy had to become a less human game.

-- [[https://www.wired.com/story/ai-diplomacy-robots/][What If the Robots Were Very Nice While They Took Over the World? | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:44])

#+end_quote

Writing is still hard for the writers (apparently).

#+begin_quote
According to Thomas Mann, "A writer is someone for whom writing is more difficult than it is for
other people." "You search, you break your heart, your back, your brain, and then--only then--it is
handed to you," writes Annie Dillard in /The Writing Life/

-- [[https://www.wired.com/story/ai-detection-chat-gpt-college-students/#intcid=_wired-bottom-recirc-v2_00a3c20c-d127-4a82-9216-e7c393a9984e_wired-content-attribution-evergreen][The AI Detection Arms Race Is On | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:24])

#+end_quote

Some things have not changed.

#+begin_quote
It's a subtle but meaningful distinction: Human writing may not be better, or more creative, or even
more original. But it will be human, which will matter to other humans.

-- [[https://www.wired.com/story/ai-detection-chat-gpt-college-students/#intcid=_wired-bottom-recirc-v2_00a3c20c-d127-4a82-9216-e7c393a9984e_wired-content-attribution-evergreen][The AI Detection Arms Race Is On | WIRED]]
(/Retrieved:/ [2023-11-06 Mon 16:30])

#+end_quote
