#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: The Unstoppable March of Technology
categories: technology artificial-intelligence
---
#+end_export

Every conversation that I have been in over the past 3 weeks outside the home has been about
generative AI, and the vein of all these conversations is quite similar. Most of the people I met
are optimistic about this new "technological advancement."[fn:2] I met a few skeptics who believe
that generative AI is adept at generating only a summary of what's already out there and incapable
of coming up with something original.[fn:4] I agree with those skeptics, based on the screenshots
that abound on Twitter and my brief experience giving a handful of prompts to ChatGPT. The apparent
inevitability of the "next thing" in technology is can not be understood as one that stems from
rational thought: Rather, it is a cultural (almost religious) belief, and it pervades in the social
psyche. For a while now, there has been this unstated acceptance that new technologies will come
along, and those who don't use them will be left behind in the dust. What if one were to ask the
question, what if the dust is good enough? One wouldn't even think of it; when has dust ever been
"good enough"?. Is the cutting edge really something you want to be on? You better want to be there,
or you will be left behind. Even if you are standing still on the travelator of technological
advancements, you will be pulled along, dragging and screaming, on the unstoppable march of
technology.

#+begin_export html
<!--more-->
#+end_export

It is *always* hard to keep up with the news. I don't read much of it anymore. Many times, I don't
know the topic that has been debated on *all the* newsletters for the past 3 days. I don't feel like
I miss many things. I find out about these things eventually, and most of the time, I am
underwhelmed by what I find out. So, I have decided to not keep up with the news and instead spend
my time on long form magazine articles, non-fiction books that try to guess where things went
wrong[fn:3], and novels that have nothing to do with the present. But even this level of
disconnection did not save me from finding out about the recent advances in generative AI
technology: Large language models.

For a long time, the goal of AI scientists was to make something that was sentient and could think
and do things like a human being. Some AI scientists thought the creation of such an AI system was
inevitable, so they started working on the problem of ensuring that these AI systems (which will
undoubtedly be created, *duh.*) don't end up adversely affecting humans. Such an AI system does not
exist yet. However, AI technology has come a long way: It can now write a mediocre essay about any
topic, which is probably plagiarizing 100s of great essays and millions of mediocre essays on the
same topic.

Another feature of this generative AI craze has been that it can write individual, isolated
functions in programming languages for things like integrating a spreadsheet with some other tool or
for connecting to the API of a service and automating some task, which was being performed
manually. This feature is probably not very scary to most software engineers; nevertheless, let me
say it aloud just once: *Most engineers are not writing isolated functions.* Their everyday task
involves making sense of the myriad ways things are done at their workplace, and figuring out a way
to make the technological stack a little bit easier to understand, while convincing a large retinue
of coworkers that what they are doing actually makes things easier. Further, this kind of
"duct-taping" between spreadsheets and some other tool is only necessary because most people agree
that the tools that they use daily at work are terrible in general and particularly bad at achieving
their primary function.

Generative AI can also create some images. [[https://www.wired.com/story/picture-limitless-creativity-ai-image-generators/][Wired magazine]] thinks that these images are better than
"art created by most humans." They declared that generative AI now has "lowercase creativity."  I
think this claim is wrong. AI art is AI art; not "human" art. There is no "authority" who can decide
what is "real" art and what isn't. So, whatever each viewer decides goes. For me, [[https://artsandculture.google.com/asset/super-chess-paul-klee/MwHvy-HH4O6BGw][a painting by Klee]]
or that of a minion by my niece is still objectively and incomparably better than the images
generated by a computer program. Despite all the dressing up of AI as some "magical system," it is
just a computer program.

Funnily enough, even [[https://www.wired.com/story/picture-limitless-creativity-ai-image-generators/][this article]] about "AI's ability to generate images that are better than art by
most humans" is *not* content with this /bizarre/ and monumental claim. Somewhere in the middle, and
completely out of nowhere, the author starts talking about how in the future you could generate 3D
images, then use that to create a world in the metaverse and then walk through it with your VR
headset. (You might notice that all the terms used in the previous sentence were coined in the 90s
and entered the public's psyche less than a year ago, when one company decided to change their name,
and make one of those terms the central theme of their *future* businesses.) A simpler reading of
the article is that it was written by somebody who has one foot in the door of every single hype
train that is leaving the station.

-----

Once, there were letters and [[https://www.youtube.com/watch?v=xQuUN1HGa0c][we used to wait]]. Then, there was the telegraph. Then, radio, television
(Idiot Box), computer, the Internet (Revolutionary), smartphones, social media (Anxiety), connected
people, and connected homes (Internet of Things). Every technology brought along some problems which
were fixed by the next /advancement/. No one stopped to think whether the adoption of each
technological advancement was necessary; whether it introduced more problems than it solved; whether
this march of technology was *really inevitable* and whether it was really a march *forward.*

Freud noticed this early:[fn:1]

#+begin_quote
Freud once pointed out that new technologies merely solve problems created by other technologies. To
the common refrain that without the telephone, we'd be unable to hear the voices of our adult
children who live hundreds of miles away, he replied, "If there had been no railway to conquer
distances, my child would never have left his native town and I should need no telephone to hear his
voice."
#+end_quote

Neil Postman, a social critic from the 1980s, spoke about it too:[fn:5]

#+begin_quote
To be unaware that a technology comes equipped with a program for social change, to maintain that
technology is neutral, to make the assumption that technology is always a friend to culture is
stupidity plain and simple. Moreover, we have seen enough by now to know that technological changes
in our modes of communication are even more ideology-laden than changes in our modes of
transportation. Introduce the alphabet to a culture and you change its cognitive habits, its social
relations, its notions of community, history and religion. Introduce the printing press with movable
type, and you do the same. Introduce speed-of-light transmission of images and you make a cultural
revolution. Without a vote. Without polemics. Without guerrilla resistance. Here is ideology, pure
if not serene. Here is ideology without words, and all the more powerful for their absence. All that
is required to make it stick is a population that devoutly believes in the inevitability of
progress.

-- p.158, Amusing Ourselves to Death (Postman)
#+end_quote

-----

*Postscript:* A list of articles that take a sober view of what is lost by always being on the
cutting edge:

1. [[https://www.noemamag.com/ai-and-the-limits-of-language/][AI And The Limits Of Language]]
2. [[https://theconvivialsociety.substack.com/p/the-prompt-box-is-a-minefield-ai][The Prompt Box is a Minefield: AI Chatbots and Power of Language]]
3. [[https://www.noemamag.com/hyperconnected-culture-and-its-discontents/][Does Digital Connectivity Democratize Culture?]]

* Footnotes

[fn:5] I found this quote on 2023-04-29 when I was re-reading Postman's book "Amusing Ourselves to
Death." Postman used the same word, "inevitable," as I had chosen to use in the opening paragraph of
this post. I am glad to find out that others share the frustration that I feel when people talk
about "unavoidable technological progress."

[fn:4] This undoubtedly depends on what you mean by "original," on which there is considerable debate.

[fn:3] We are all in tacit agreement that things have gone terribly wrong, right?

[fn:2] It is interesting that the change has been characterized as an advancement even before it is
completely clear what the change really even is.

[fn:1] *Author:* Meghan O'Gieblyn. From the "Dear Cloud Support" column in the February 2023 issue
of Wired magazine.
