# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Siddharth Kannan's Blog
tagline:          'Cogito ergo sum.'
description:      'Cuber | Programmer | Pianist. <br/><a href="http://icyflame.github.io">@icyflame</a>'
baseurl:          https://icyflame.github.io/blog/
baseurl_without_slash: https://icyflame.github.io/blog
disqus_shortname: siddharthkannanblog

author:
  name:           'Siddharth Kannan'
  url:            https://icyflame.github.io/

paginate:         5

# Custom vars
appname: 		  blog
version:          2.1.0

github:
  repo:           https://github.com/icyflame/blog
