# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Siddharth Kannan's Blog
tagline:          'Cogito ergo sum.'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:      'Cuber | Programmer | Pianist. <br/><a href="http://icyflame.github.io">@icyflame</a>'
# url:          http://icyflame.github.io/hyde/
baseurl:          http://icyflame.github.io/hyde/

author:
  name:           'Siddharth Kannan'
  url:            https://icyflame.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
