# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "Siddharth Kannan's Blog"
tagline: 'Cogito ergo sum'
description: 'Programmer | Pianist <br/><a href="http://icyflame.github.io">@icyflame</a>'

baseurl: https://blog.siddharthkannan.in/
baseurl_without_slash: https://blog.siddharthkannan.in

disqus_shortname: siddharthkannanblog

author:
  name: 'Siddharth Kannan'
  url: https://icyflame.github.io/

paginate: 10

# Custom vars
appname: blog
version: 2.1.0

github:
  repo: https://github.com/icyflame/blog

plugins:
  - jekyll-paginate

# Don't put categories at the top of the links
# permalink: /:year/:month/:day/:title
