* Blog
:PROPERTIES:
:CUSTOM_ID: blog
:END:

#+begin_quote
A blog-aware site, using Jekyll, hosted on GitHub Pages.
#+end_quote

** Deployment
:PROPERTIES:
:CUSTOM_ID: deployment
:END:
This is a blog-aware site that is built using the static site generator
Jekyll.

The initial configuration of this site put the list of tags in the link of each blog post. The link
structure was =/tag1/tag2/.../tagN/YYYY/MM/DD/post-stub/=. These links are long. More importantly,
they prevent recategorization of posts as that would break the link of the posts. So, I switched to
the concise link structure =/YYYY/MM/DD/post-stub/=.

However, the blog had already been online for several years when I made this switch. So, I wanted to
support both the initial link structure and the new link structure for *all* posts. To do this, I
wrote a simple GitHub Actions workflow which generated the website using both link structures and
merged the two folders together using =rsync=.

*** Current configuration
:PROPERTIES:
:CUSTOM_ID: current-configuration
:END:

- Branch with the posts: =master=
- Branch with built site: =published=
- Path of the site inside the =published= branch: =docs/=

** Development
:PROPERTIES:
:CUSTOM_ID: development
:END:

Last updated: /2022-10-13/

Ruby version: *3.1.2*

*** Setting up

1. Install rbenv
   1. https://github.com/rbenv/rbenv
2. Install ruby version 3.1.2
   1. rbenv uses [[https://github.com/rbenv/ruby-build#readme][ruby-build]] to install Ruby versions

#+begin_src sh
  $ rbenv local 3.1.2
  $ gem install bundler
  $ bundle install
  $ make serve-dev
#+end_src

** Scripts
:PROPERTIES:
:CUSTOM_ID: scripts
:END:

*** Publish an org file inside the =posts-org= directory
:PROPERTIES:
:CUSTOM_ID: publish-an-org-file-inside-the-posts-org-directory
:END:

#+begin_src sh
make publish-single FILENAME=posts-org/post.org
#+end_src
