#+TITLE: Strength of the Counter-Argument to Public Advocacy
#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Strength of the Counter-Argument to Public Advocacy
categories: covid19 arguments philosophy
---
#+end_export

On Dec 10th 2020, Zeynep Tufekci made [[https://zeynep.substack.com/p/vaccines-and-decision-making-with][a public argument]] for a trial of the single dosage of the
Pfizer and Moderna mRNA vaccines on her mailing list, Insight. When I first read the argument and
it's basis on the apparent safety and efficacy of just the single dose of the Pfizer/BioNTech
vaccine, as described in the [[https://www.nejm.org/doi/full/10.1056/NEJMoa2034577][official peer-reviewed paper]], I agreed with Tufekci. Her argument is a
solid one and poses the central question: *Is vaccinating 95% of 50% of available doses better than
60-80% of the total available doses?* The answer is equally simple: *No one knows yet*. Some
inferences can be drawn from the data of the 1300 people who didn't get the second dose in the
original N = 40,000 clinical trial. But this subset of 1300 people is not as random as the original
well-designed trial. Another clinical trial, the advocacy for it in as many public forums as
possible and subsequent funding / trial design seems like the prudent way to go forward, as Tufekci
describes in her post.

On Dec 30th 2020, Tufekci posted philosophy professor,[[http://www.matthewnoahsmith.net/][Matthew Noah Smith]]'s [[https://zeynep.substack.com/p/a-counter-argument-against-public][counter]] to her original
argument on Insight. I read that post today and found it to be particularly weak. This post goes on
to explain why I felt that, and the peculiarities in Smith's post.

#+begin_export html
<!--more-->
#+END_EXPORT

The post intrigued me because I was looking forward to a rousing philosophical debate on the greater
implications of whether public advocacy was really flawed in high-stakes situation. Unfortunately,
the post doesn't go much beyond this particular case.

For context, the number of available doses hovers around 50 million for the US right now. This
question is already being faced by several other countries (Indeed, the UK has [[https://www.politico.eu/article/uk-chief-medics-justify-single-dose-coronavirus-vaccine-strategy/][decided to go ahead]]
with the single dosage regimen).

#+begin_quote
As can be seen, the incidence of Covid-19 drops off dramatically about 10 days after the first dose
(look at the chart on the top left). However, the trial is designed to measure the efficacy of two
doses: a prime and a booster. Eyeballing (we don’t have the underlying data), the first shot seems
to have 65-80% efficacy in the full group—but we don’t know for how long that lasts.
#+end_quote

One might argue accurately that countries scarcely have the time to accommodate philosophical
arguments, that the best thing to do right now is the thing that will reduce short-term and
long-term adverse outcomes. I will table that for the time-being.

Putting that aside, here are some things that I couldn't reconcile within Smith's argument, that
ultimately lead me to believe that Smith's argument is weak.

* The cautious optimism/overt pessimism fork in attitudes

Here are some quotes from Smith's article:

#+begin_quote
It is more difficult to weaponize technical language used in academic journals and grant
applications than it is to weaponize exasperated charges of epistemic irresponsibility made in
places like Twitter. For this reason alone, we should restrict calls for single-dose trials to
venues where experts engage other experts.

...

Bad actors with power have regularly harmed marginalized communities in the name of science. This
same pattern of oppression could be reproduced when it comes to vaccine distribution. ... The
rhetoric around a single-dose trial could be twisted by people as a pretext for denying second doses
[to] the marginalized. (sic)

...

This plays into the pernicious pandemic wartime imaginary we've all been invited to take up. Doctors
and nurses are "heroes" who have been at the "front lines," and hospitals are "war zones." Once we
couple this with the firm conviction among conservatives that the police are a beleaguered identity
group, an easy strategic choice in response to vaccine distribution woes will be to deny poor
communities and communities of color both doses of the vaccine until all those "battling" the virus
receive two doses.
#+end_quote

I find that the fork in Smith's argument's attitudes towards similar groups of people remains
_unresolved_: Smith is *very optimistic* that the conservative media will _not_ find an article or
letter in the Journal of the American Medical Association (JAMA) or find it hard to exploit; while
being *extremely pessimistic* about the outcomes of public advocacy: namely, a coordinated and
racist effort to ensure that police officers and other "front-line" workers will be given a 2-dose
vaccine regimen, at the cost of the poor, homeless, and other vulnerable demographics; all of whom
also have the least access to healthcare.

This dichotomy is hard to reconcile. The conservative media and the government bureaucrats and
lackeys that Smith is splitting up in his article are both on the same side of the political
spectrum, and _ostensibly_ very close to each other in terms of both social and economic
policies. Why would one group be particularly restrained about legitimizing single-dose regimens
using a JAMA letter, whereas the other group would use a public version of the same content, to
actively prevent particular people from being vaccinated? One must argue _either_ that they are all
con-artists who want to find the slightest shred of scientific doubt, and use it to exclude people
_or_ that they are restrained, well-intention-ed actors, whose moral threshold for converting
scientific doubt into a strategy, lies somewhere between a New York Times article and a JAMA
letter. Smith seems to be arguing for the former, but this quote is an outlier and doesn't make it
too far.

#+begin_quote
All they need is quasi-scientific cover for unequal spatial distribution of a two-dose vaccine
distribution.
#+end_quote

Smith's overt, almost militant, pessimism towards the prevention of the second dose for a particular
group of people seems unnecessary and hard to justify: Even if it was just informal policy, any
widespread attempt to deny second vaccine doses will quickly become a big story in the Liberal
media. Moreover, states where the state legislatures are Democrat-controlled do exist (albeit, they
are in the minority). Vaccine efficacy rates in these states will be much higher even when the same
number of doses per-capita have been doled out; scientists and pundits will both be hard-pressed to
find the reason and this (in)formal policy would be the primary suspect.

* Are Technical articles harder to exploit for political gain?

#+begin_quote
While it is impossible to prevent cynical politicians from weaponizing science for short-term gain,
simple precautions should be taken. One tactic is to avoid turning a scientific disagreement into
acrimonious public disagreement. It is more difficult to weaponize technical language used in
academic journals and grant applications than it is to weaponize exasperated charges of epistemic
irresponsibility made in places like Twitter.
#+end_quote

The second peculiarity in the argument is that Smith vehemently believes that it will be
considerably harder to demonize the kernel of scientific doubt, inherent in everything, if that
doubt is expressed in a JAMA letter, whereas it will be far easier to exploit if it was done through
a post on Tufekci's blog, a New York Times article, and a press conference at Harvard. Considering
that the conservative media is made up of competent institutions which have researchers combing
through public discourse to find chinks in the armor of the 2-dose vaccine regimen's requirement,
there is no doubt in my mind that they would find the JAMA letter. Given that base assumption, what
makes a JAMA letter harder to exploit? The content would have been the same. Smith says the same
thing, "All they need is quasi-scientific cover for unequal spatial distribution of a two-dose
vaccine distribution.", although this acceptance doesn't affect his underlying argument.

Going one step further, I argue that the JAMA letter approach would be detrimental to Tufekci's
cause, as the journal article would have *far fewer readers*. It would not enter the organic news
feeds that are consumed by people who don't get their news from conservative media. They might even
come across the article _first_ through coverage of conservative media on other media outlets as a
"Factcheck" or as "Media critic", which substantially reduces the power of the advocacy.

The story that deserves to be publicized is *not* the one that the Conservative media took a JAMA
letter and mis-categorized it. This would invariable be what goes into the feeds watched by Liberal
news consumers. The coverage of the story will become the story, similar to [[https://youtu.be/yFsyfXEENPU?t=131][CNN coverage]] of the
Healthcare bill's repeal.

In fact, in the quote at the beginning of this section, Smith seems to accept that it's impossible
to prevent cynicism, and that these would simply be measures that _might_ work. Weighing the
argument for a single dose trial (which could potentially double the number of vaccinated people)
*against* the off-chance that cynical politicians and media outlets on the right will be _sloppy_
and _miss_ a JAMA letter, the former's superiority, in terms of better, wider, positive outcomes, is
clear to me.

* Tufekci's argument's coverage will mislead non-medical observers

My final qualm with Smith's argument is his belief that the stories covering the strategy that
Tufekci took will be confusing or misleading, even if they don't intend to be.

#+begin_quote
Even though the public message is that we should trial a single-dose vaccine, it is reasonable for
someone unfamiliar with how medical research works to infer from a news story about the proposal
that a single dose would be sufficient for vaccination. Furthermore, it is reasonable for someone
who sees a story on TV about a study of single test efficacy to then describe it to acquaintances as
a story about how only one dose of the vaccine is needed. After all, isn't it rational for these
non-experts to infer from respected professors aggressively advocating in public for a single-dose
trial that a single dose would be sufficient? Why else would they be so vocal and so insistent on
the urgency of a trial?

...

The intensity of emotions around these issues does not make trivial, often ersatz, scientific
disagreement less likely to be perverted into a tool to discredit even the most widely accepted
views.

...

What will happen if rhetoric supporting a single-dose trial is weaponized? It is difficult to
determine. We have some evidence from both this pandemic and the anti-vax movement that non-trivial
portions of the population might, on the basis of the weaponization of public advocacy for a
single-dose trial, reject public health guidelines around vaccination.
#+end_quote

This lies in direct contrast to something that he says just a few paragraphs before:

#+begin_quote
If a trial is warranted, then we ought to have some confidence that a single dose of either vaccine
would be effective. But we also should have sufficiently low confidence that a single dose would be
effective. This is exactly why a trial is necessary.
#+end_quote

Smith seems to be saying that non-medical readers will somehow "miss the point", even in good faith
coverage of Tufekci's strategy. I don't think this is true or fair. The problem is not with the
coverage, but with how most people consume the news: in short bites, as web page titles OR the first
2-3 minutes of a YouTube video describing the story. A consumer who reads Tufekci's article, even
just the first few paragraphs, will _not_ come out believing that a single dose is better or
efficient _enough_. To her credit, the article on Tufekci's blog doesn't even mention her argument
in the title. It is a broader appeal _for_ effective policy-making in the absence of sufficient data.
