#+OPTIONS: author:nil toc:nil

#+begin_export html
---
layout: post
comments: true
title: Climate Change Fever, Late 2021 Edition
categories: climate-change global policy governments
---
#+end_export

If you haven't caught the climate change fever yet, you almost certainly /will/ catch it in the next
few weeks. Even a cursory glance of the news will familiarize you with [[https://ukcop26.org/][COP26]]. As the climate
conference approaches, Western publications have [[https://www.bloomberg.com/green-cop26-climate-summit][gone]] [[https://www.nytimes.com/2021/10/27/climate/nyt-climate-newsletter-cop26.html][all-in]] and bet that the conference will
generate a large amount of news. They are right about this, the conference is definitely going to be
a hotbed of some /stunning/ news stories. Some countries might announce new targets, others might go
back on their existing targets or not commit to anything new, etc. Every change in policy will be
followed extremely closely and dissected and analyzed from every possible angle. Only one question
will remain unanswered: *What is the point of all this hoopla?*

#+begin_export html
<!--more-->
#+end_export

Climate change science and climate change activism are no longer distinct. Scientists and activists
used to occupy different positions in the discourse, as [[https://www.slowboring.com/][Matt Yglesias]] has pointed out
before. Science is about trade-offs, because very few things come at 0 or near-0 costs. Activism is
about convincing other people to share your beliefs and implement your proposals, and thus,
selecting evidence that will help you achieve that end and ignoring evidence that will hurt your
ability to achieve your goals is ethically acceptable to an activist.  Returning to a Matt Yglesias
quote,[fn:1] "If you are an activist and you are admitting that there are trade-offs to your
proposals, then you are doing activism wrong."

When it comes to the topic of climate change, scientists often speak like activists, issuing dire
warnings about the devastating effects of a warming planet. Activists speak like scientists, armed
with information that has become [[https://www.bloomberg.com/graphics/climate-change-data-green/][ridiculously easy to access and easier still to understand]], as it
has been boiled down to a few numbers. Never mind if the numbers actually tell the story that a
naive interpretation of them would suggest.

Politicians occupy a sticky position in this discourse. Their /job/ is to reflect the majority's
thoughts back at their voterbase. On an issue such as this one, it is nearly impossible to poll the
right number of people and find out what the majority thinks. This has crippled the political
response.

Some [[https://twitter.com/aoc][activists]] have become politicians but have not changed their role as their constituencies are
so "in the bag" that what they say or do is completely immaterial. AOC's [[https://youtu.be/FGVW9vJ773k][recent questioning]] of
executives from big oil was a good instance of toxic, futile posturing. I believe that smart,
sarcastic coverage of Big Oil has always hit the mark in convincing people of the shady roles that
Big Oil and their lobbyists play in the lives of the citizenry and how they are warping (education,
energy and economy) policy. Laura Grey's [[https://youtu.be/-VojHT92LGI][segment]] from the show, The Opposition with Jordan Klepper,
is a good example of such coverage.

In the face of [[https://www.politico.com/news/2021/10/28/climate-summit-agenda-half-baked-biden-517462][opposition]] /even/ from members of their own party in countries like America,
politicians have ended up facing the reality that is clear to neutral observers: The economy is
deeply tied to the technologies which the climate change activists say must be eradicated and the
economy is one thing that has real impact on people's lives and swings elections.

The media has undoubtedly taken a side. Articles about how COP26 is the place where most problems
will be solved are commonplace. "The importance of this summit cannot be overstated," "It is high
time that the leaders of the world get together and do /something/ about this /existential
threat./," "Rich nations have a responsibility to the global poor," "Poor nations that continue to
pollute must be penalized by rich nations," and so on. The unending contradictions are impossible to
parse.

But there /is/ *one* specific talking point that I want to delve into.

* Who Is The Biggest Polluter?

Most publications and activists point at India and China as the biggest polluters. This is an
intentional jibe and a mischaracterization of the issue at hand.

Here's the table of emissions and populations, sorted by annual emissions. (A note about
abbreviations can be found in the footnotes[fn:2].)

| Country | [[https://ourworldindata.org/grapher/total-ghg-emissions?tab=chart&country=USA~GBR~CHN~IND~JPN][Annual GHG emissions]] (billion tonnes) | [[https://data.worldbank.org/indicator/SP.POP.TOTL][Population]] (billions) | [[https://ourworldindata.org/grapher/ghg-emissions-per-capita?tab=chart&country=USA~GBR~CHN~IND~JPN][GHG emissions per capita]] (tonnes) |
|---------+---------------------------------------+-----------------------+-----------------------------------|
| *China* |                                 10.17 |                 1.402 |                              9.22 |
| America |                                  5.28 |                 0.329 |                             20.20 |
| India   |                                  2.62 |                 1.380 |                              2.38 |
| Japan   |                                  1.11 |                 0.125 |                             11.59 |
| England |                                 0.369 |                 0.067 |                              9.20 |

Indeed, China appears to be the largest polluter. Sorting this table by per-capita emissions tells a
different story.

| Country   | [[https://ourworldindata.org/grapher/total-ghg-emissions?tab=chart&country=USA~GBR~CHN~IND~JPN][Annual GHG emissions]] (billion tonnes) | [[https://data.worldbank.org/indicator/SP.POP.TOTL][Population]] | [[https://ourworldindata.org/grapher/ghg-emissions-per-capita?tab=chart&country=USA~GBR~CHN~IND~JPN][GHG emissions per capita]] (tonnes) |
|-----------+---------------------------------------+------------+-----------------------------------|
| *America* |                                  5.28 |      0.329 |                             20.20 |
| Japan     |                                  1.11 |      0.125 |                             11.59 |
| China     |                                 10.17 |      1.402 |                              9.22 |
| England   |                                 0.369 |      0.067 |                              9.20 |
| India     |                                  2.62 |      1.380 |                              2.38 |

Both America and Japan are far bigger polluters, per resident of their nations. Looking at
per-capita emissions seems like the obvious method for assigning blame because the number of people
in a country is the only constant which can't be changed, in the lack of drastic changes like a
war.

The high GHG emissions are due to the level of advancement of these countries, which entitles them
to uninterrupted electricity, cheap gasoline, higher levels of disposable income leading to far more
air travel, etc. These advancements are objectively good things for the populations of these
countries and not something to be looked at grudgingly or that countries should be penalized
for. So, hiding behind the "Annual GHG emissions" number is a dodge from the media. They
recognize the failure of the US and Japan to take any action; and they channel this recognition into
an effort to reassign blame to China, a poorly understood nation without the power of a persuasive
English media ecosystem.

-----

As the failure of the [[https://www.vox.com/future-perfect/22408556/save-planet-shrink-economy-degrowth][degrowth movement]] (even in the most liberal parts of the world) has shown, the
solution that holds sway among populations is not one which involves a compromises of any kind. So,
any rhetoric about how "human beings have hurt the planet and its time we suffer to redeem
ourselves" is useless.

Griffith's [[https://www.vox.com/podcasts/2020/8/27/21403184/saul-griffith-ezra-klein-show-solve-climate-change-green-new-deal-rewiring-america][vision]] is a solution that involves retaining the same level of comfort but changing the
energy sources to ones that have lower emissions for producing the same amount of energy. But as
Griffith admits, the problem is not one of engineering, it is one of *political will.*

So, as you look at the coverage of the COP26 summit, bear in mind that the summit exists only to
convince people in the speakers' countries that /their country is doing enough/ and that the /cause
of inaction is abroad./ The likelihood of any major treaty emerging from this summit is low,
especially given that the world's largest polluters are stuck in political limbo with [[https://youtu.be/-Obru_ndWRw][a polarized
voter base]].

There will be a lot of "symbolic" announcements[fn:3] and these will be celebrated in lieu of the
/real/ action that this conference was supposed to coerce out of nations. The blame-game [[https://www.nytimes.com/2021/10/28/business/energy-environment/china-coal-climate.html][against
China]] and India's refusal to commit to any new net-zero goals will continue unabated.

[fn:1] This quote is from [[https://www.vox.com/2020/9/18/21445417/one-billion-americans-matt-yglesias-the-ezra-klein-show][Matt Yglesias' appearance on the Ezra Klein Show podcast]] in late 2020.
[fn:2] *Note:* 1. GHG = Greenhouse Gases; 2. CO_2 equivalent: Equivalent emissions of CO_2 gas if the emitted gas is not CO_2
[fn:3] Such as [[https://www.bloomberg.com/news/articles/2021-10-23/world-s-biggest-oil-exporter-commits-to-net-zero-emissions?utm_source=webpush&utm_campaign=BreakingNews%7CStory%7CR1BSYOT0AFB601][Saudi's commitment to Net-Zero in 2060]]; a commitment that does *not* involve a
reduction in crude oil production and is focused only on the consumption of fossil fuels inside
Saudi Arabia.
