#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: The Midnight Assemblies
categories: iit-kgp india orientation-program
---
#+end_export

"The night is dark and full of terrors" - Parents use phrases like these to put children to sleep
and to curb their adorable natures and their inexhaustible reserves of energy, which enable them to
run around, squealing in delight, until all hours of the night. On exiting childhood, most people
discover the deception that their parents had engaged in. The second years living in the Nehru Hall
at IIT Kharagpur had a remarkable experience: For them, the terrors returned and their parents were
proved right. They were woken up at odd hours of the night, requested to demonstrate the skills they
had learned in the [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/11/orientation-program-iit-kharagpur-part-2/][common room]] and the [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/12/orientation-program-iit-kharagpur-part-3/][dining hall]] and subject to a series of deranged
meditations. These polite requests were unlike those that some might be accustomed to, as they were
made by third-, fourth- and fifth-years who stood in the first-floor corridor and directed their
voices downwards towards throngs of second-years who stood in neat rows on the playground. *This*
was the final form that hazing at IIT Kharagpur, affectionately referred to by the euphemism,
"Orientation Program", or simply, O.P, assumed. I recount my experience of O.P. in this 4-part
series. This is the fourth and final part, The Midnight Assemblies.

#+begin_export html
<!--more-->
#+end_export

On a few days in September and October each year, a group of third years would go to the top floor
of Nehru Hall at midnight and begin waking up all the second-years who lived there. An onlooker
might ridicule these amateur explorers; why! Some might even go so far as to call them
malevolent. Allow me to dispel that notion: They were not malevolent; in fact, their intentions were
pure. They aimed to better the lives of the second years who had had the good fortune of being
assigned to this particular hostel through /education/, education that the institution can't (or
won't) provide.

A part of the inscription on the Statue of Liberty says that tired, poor and huddled masses yearn to
breathe free. What about the masses who are already free?  How can one awaken this yearning within
them? These third-years had the answer: turn the free masses into tired, sleep-deprived and
resentful masses, so that they might rediscover their freedom. Philosophers have oft-repeated that
losing what you believe you are entitled to is the only way to understand it's true value. Today, I
go to sleep knowing that not a single deranged person out there can awaken me to serve a strange
power trip. That expectation, which is taken for granted by most, was a luxury when I was in
college.

On a night like this one, an unbiased observer would witness several third-year students walking
with impunity through a floor full of sleeping second-years. The observer would see them banging
loudly on doors and peering shamelessly through cracks in windows. The observer would notice them
relishing their power and reveling in the authority that had been bestowed upon them by
Nature[fn:2]. They would be seen employing /such innocuous/ strategies as entering uninvited into a
room whose door had been left ajar, turning on the bright light or tapping sleepers on their
shoulder in a not-totally-pleasant manner.

While the third-years performed their part in this exercise, they did not bother to hide their
activities or "keep it down". They feared no retribution. Unlike other hostels in India, the warden
and the hall managers did not actually sleep in the hostel. They were probably asleep in their
homes, dreaming about spending as little time as possible inside the hostel and ensuring that all of
it was during the work-day[fn:3]. The only remaining adults in the hostel at midnight were the
security guards, tasked with keeping bad people out of the hostel. They did not have any
responsibility for the activities of the people who were already in the hostel though, no matter how
morally corrupt they were or could be.

The hostel's security guards were curious adults nevertheless. As soon as they realized that what
happened every year was happening this year as well, they would scurry around and make themselves
scarce. This was due to a welling up of /noble self-interest/. "Do not meddle in that whose
conclusion is unknown to you" were the words they repeated in prayer each night. No one knew how the
night was going to turn out or where the activities might lead this year. So, it would be most
unfortunate if one were not to have access to the vital weapon in the coward's arsenal: *Plausible
deniability*.

A strain of arbitrariness runs through this narrative: Why wake people up at midnight? Why not
before? Why wake them up at all? What could be gotten from this deprivation of one's own sleep and
that of strangers who clearly wished to remain uneducated? The first 2 questions can be answered
satisfactorily. While throughout the day, second-years went in and out of the hostel as they
pleased, everyone returned to their rooms at night. Being used to sleeping in their own bed
undisturbed, after a day full of activity, the second-years had underestimated the diligence of
their preachers and tormentors, who would gladly give up a night of sleep, if it meant that they
could get drunk on power.

After waking the second-years up, they would be lead down to the playground and asked to stand in
neat rows. Once this part was complete, the third-years went about summoning the bishops who would
deliver the day's sermon. These consisted of some fourth- and fifth-years. The people who held the
titles of "Hall President (HP)" and "Hall Vice President (VP)" were invariably present and jointly
played the role of the Master of Ceremonies. These titles were lofty and meaningless to the real
world, as the letters of the alphabet are meaningless to an infant. Nevertheless, the play-acting
continued. An infant immensely enjoys playing with a building block in the shape of the letter A and
fully grasps the meaning and purpose of that building block: gratification of her desire to *have a
good time*. And so the person who called himself the "Hall President" believed that there was
meaning in the title as it served his purpose: the realization of their fantasy of wielding
/power/ over people who would never voice their opinion and inconvenience him.

The first things that the bishops noticed were the minor misalignments in the assembly: someone who
was not neatly lined up, someone else who was sleepy. They took pains to point the person out and
put them in their place by extolling on the virtues of discipline. In this regard, they behaved like
a drill sergeant who had said something incredibly stupid and was being teased by his
subordinates. Feeling anger rise up in his throat, the drill sergeant is harsh with his subordinates
for the next few days. It's not a proportional revenge; it is the only thing he *knows* how to
do. If the thought that he should /try/ and not make a fool of himself in the future had entered his
mind at all, he did not give it away.

After the assembly was perfect and everyone was in line, the bishops began their sermon. I am
certain the reader will excuse me for not remembering the content due to the exceedingly drowsy
state I found myself in during these occasions. As these were fifth-year students who had the time
and /willingness/ to preach from a first-floor balcony at 1 a.m., one can safely assume that the
content was primarily non-academic. My faint memory does contain a few choice nuggets of
[[https://www.youtube.com/watch?v=Cv1RJTHf5fk][/knowledge/]], akin to the crude teachings of 20-minute TEDx talks. Admittedly, they will be of no
value to competent adults who managed to stumble into a workplace with respectful coworkers.

I remember one astonishing detail clearly. A few of the sermons were blessed by the presence of *an
alumnus* who used to live in this hostel: An adult who had returned from the real-world and was now
standing at a balcony at 1 a.m., discoursing at 100s of second-years whom he felt an inexplicable
connection with, despite being a complete stranger to them. "It doesn't make any sense!", some of
you might be exclaiming. Well, I can only say that your passion for your living quarters did not
match that of those who had returned back to IIT Kharagpur and were [[https://www.youtube.com/watch?v=SlBtQZnm_68][reliving their glorious college
days]], possibly wresting back the power they /had/ held once-upon-a-time.

The sermon regularly lasted anywhere between an hour and 3 hours. It did eventually end, but the
party was not over yet.

After this late-night / early-morning sermon, one of the rituals was a "Tempo Shout". It involved
the assembled sleep-deprived second-years getting together in a circle, getting ready to sing
[[https://en.wikipedia.org/wiki/Kumbaya][kumbaya]] and shouting things. With hoarse voices, a lot of resentment, little energy, and even less
respect for the seniors gazing upon them wistfully from the first floor, these students shouted the
things that they were told to shout. Even those participants who were determined to deal with
everything that was happening as a mere joke, which they alone were in on, gave up and participated
wholeheartedly.

Another post-sermon activity can be explained only through psychology, due to its puzzling nature
and the warm reception it received among members of the congregation. After the sermon, the
tormentors and the tormented walked to a dilapidated food stall at the entrance of the college
/arm-in-arm/. This stall served food rich in carbohydrates (namely, [[https://en.wikipedia.org/wiki/Maggi_noodles][Maggi]]). Seniors showed their
magnanimity by buying these plates of food for the second years who had been up all night and could
look forward to a wretched, sleep-deprived, confusing day, which was made better only by the
knowledge that they had learned /important/ life lessons which remained hidden from their
well-rested friends who lived in other hostels.

With this, the priming process that began in the [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/11/orientation-program-iit-kharagpur-part-2/][common room]] several weeks ago was finally
complete. In 2014, O.P. at Nehru Hall was a resounding success.

-----

*Programming note:* This is the fourth and final part of a 4-part series. New posts will be
published at 11 am UTC (4:30 pm India, 8 pm Japan).

| Post                                                  | Date           |
|-------------------------------------------------------+----------------|
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/10/orientation-program-iit-kharagpur-part-1/][The Curious Case of the Dweller Who Wouldn't Move Out]] | 10th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/11/orientation-program-iit-kharagpur-part-2/][The Sermon in the Common Room]]                         | 11th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/12/orientation-program-iit-kharagpur-part-3/][Victorian-era Dining Hall Etiquette]]                   | 12th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/13/orientation-program-iit-kharagpur-part-4/][The Midnight Assemblies]]                               | 13th May, 2021 |

-----

[fn:2] For they were born 1 year before the second-years now being rudely awakened from their
slumber.

[fn:3] The work-day for hostel workers in IIT Kharagpur began at 3 pm and ended at 5 pm.
