#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: The Sermon in the Common Room
categories: iit-kgp india orientation-program
---
#+end_export

As a second year student at IIT Kharagpur, the 2.5 months between July and September 2014 were
uneventful at Nehru Hall, one of several hostels inside the campus. Then, things took a turn. While
I believe that it was for the better, the voice at the back of my head believes it was for the
worse. In this post, I relate the story of a sermon that was delivered in the common room of my
hostel. The sermon in question was about the art of introducing oneself to a group of
strangers. While many might naively believe that they have mastered this art, this sermon will open
your eyes (as it did mine) to the /right/ manner of making a first impression. *This* was an
integral part of hazing at IIT Kharagpur, affectionately referred to by the euphemism, "Orientation
Program", or simply, O.P. I recount my experience in this 4-part series. This is the second part,
The Sermon in the Common Room.

#+begin_export html
<!--more-->
#+end_export

Before the sermon, comes the priming. The preacher must establish his preeminence, ease the
congregation into the environment where the sermon will be given and familiarize the congregation
with the tone that will be used. In 1973 in an undisclosed location, a process similar to this
priming is said to have taken 6 days. In that case, the pressure was higher and the stakes hardly
comparable, and the results left experts baffled at this technique's effectiveness in endearing the
preacher to the congregation. In Kharagpur in 2014, it took about 10 days and achieved /similar/
results.

On the first day, all the second-year students were /courteously invited/ to the hostel's common
room, at 9 pm right after dinner. To the uninitiated, this sounded like a friendly invitation to get
to know the seniors who were living in the same hostel: everyone studying in 3rd year and above. The
assembly was moderately successful and about 100 people sat on the floor in a well-ventilated
room. A group of about 15 third-year students introduced themselves in-turn. These students were
central to the organization and smooth execution of O.P. Nothing in their introductions stood out
and I shudder to even imagine my inattentiveness during this part. After the introductions, there
were some "general" announcements and calls for auditions for various hostel teams: athletics, team
sports, dumb charades and so on.

These calls to auditions were courteous: "If you can swim and want to be a part of the hostel's
swimming team, then talk to the captain of that team". Then, the captain would take the stage and
make a pitch to get people to come to the auditions or try-outs for their team. All the captains
succeeded at making participation in hall activities sound like noble pursuits. These teams would
compete in a yearly extravaganza known as the General Championships (or G.Cs) in which hostels
competed against each other in a variety of competitions; points were awarded to the victor and the
championship was awarded to the hostel with the most points. Every hostel had won this championship
at some point in the past. Nehru Hall was no exception. But the captains were skilled pitchmen and
made winning the GC sound like an exceptional achievement that no one else was capable or worthy
of. They stressed that no other mere "hostel" could win the GC, because of the sheer desire that
thrived /exclusively/ at Nehru "hall".

A rational member of the congregation might be expected to ask, "Well, how come you didn't win the
GC last year? Or the year before that? Or once in the past 5 years?". I have never seen anyone
asking questions at a sermon though, so I believe such a question would have been highly
inappropriate. If asked, the question would have provoked a lively discussion about the /reason/
that the GC was not won by /our/ "hall": *Collusion between the external judges of an event and the
people living in other hostels*. These theories covered a lot of ground and the preachers did not
balk at hurling allegations far-and-wide: "The judge was another hostel's hall president's nephew's
mother's colleague's son's Guitar teacher! That was clearly the reason for the blatant bias shown by
the judge during the event last year".

These theories also included the Secretaries of each event, student representatives who were tasked
with conducting the events and whose job it was to find judges for each event. These Secretaries
were elected through an election where students voted and they were often from other hostels. The
mere fact that the people who were choosing the judges were from a "hostel" was proof for many that
there was a massive conspiracy against our "hall".

On listening to this answer, the rational member who had asked the question would fall silent and
introspect quietly at the lack of wisdom which had caused them to begin this discussion. Everyone
else thought about the theories just put out and continued to listen with rapt attention to the
preachers, who were talking about fantastical things that had happened in the past which had lead to
the crushing defeat of /our/ hall in the G.C.

The number of spectators during these post-dinner "group hangs" in the common room remained steady
with mostly repeat participants. I was fascinated by the determined group of preachers who had taken
it upon themselves to educate the second-year students. What other proof could I provide of their
magnanimity to you, dear reader? This priming period worked phenomenally well as the third-years
conducting these sessions quickly rose to prominence in second-year circles and were revered as
people whom one could look up to for advice in a tough situation.

On the 11th day, things changed dramatically. While there was no outward change in the structure of
the session, there was more shouting; much, /much/ more shouting. The topic of this session and
several sessions after this day was deceptively simple: Introducing oneself to a group of
strangers. The techniques would also be effective if one were trying to pacify an angry mob.

Third years who were 19 years +old+ young deigned to teach 18 year old second-years how to introduce
themselves /properly/ to a group of strangers. The script was simple:

#+begin_quote
My name is [INSERT NAME HERE].

I am a 2nd year student at the Department of [DEPARTMENT] at IIT Kharagpur.

I live in Nehru Hall and my hobbies are [HOBBY 1, HOBBY 2].
#+end_quote

The reader might well want to point out that this script makes a lot of sense and conveys
information about the speaker to the audience concisely. I wholeheartedly agree with the
reader. Although, it would be wise on the reader's part to reserve judgment on this whole exercise
until /after/ I have related the instructions that came with this script regarding how it should be
delivered.

The preachers preached, the /tenet of utmost importance/ when introducing oneself was to be
/confident/. Confidence being one of the non-verbal parts of communication, one must take extra
pains to verbalize it. To this end, the preachers implored each second-year in the audience: When
introducing yourself, *SHOUT AT THE TOP OF YOUR VOICE*.

After listening to a demonstration, I would offer an alternative characterization which will be
easier to imagine if you are an avid horror movie watcher: *SCREAM LIKE THE CHARACTER WHO HAS JUST
SEEN A GHOST*.

Once this tenet was revealed, the time was ripe for some /hands-on learning/: *blameless* exercises
where a second-year student was asked to stand-up and deliver their self-introduction. If the
student stumbled on any part of their introduction, the preachers asked him to start again, by
shouting *loudly* at him. The preachers shouting makes complete sense as they were only being
confident and not chastising the student in any way at all, in fact they were being very supportive,
evidenced by both their mocking and their constant interruptions.

The preachers had noticed what I have long noticed about confident people. When confident people
talk, it is clear to the listener that (a) they have rehearsed what they are saying a few hundred
times, (b) they /never/ pause to collect their thoughts, and (c) they do not change their response
depending on the audience. The well-rehearsed delivery with no hiccups makes the speech sound
natural, unlike the pre-recorded mechanical voice without any emotion that one hears when
computerized assistants like Alexa or Siri introduce themselves. The lack of any breaks in the
speech indicates that the speaker does not need to burden their brain with thinking or
introspection. And the constancy in content irrespective of the audience is the pinnacle of the
egalitarian principle[fn:2].

Further, the preachers preached, when introducing yourself, *look /every person/ in the audience
straight in the eye*. The naive student of human anatomy would quickly retort that this is
impossible; that to achieve it one would have to unnaturally oscillate their head, tracing a
semicircle with the tip of their nose. They would also add that moving your head around like an
automaton would make the listeners uncomfortable due to the uncharacteristic juxtaposition of the
confident, not-at-all automaton-like voice shouting at them and the robotic movements. The preachers
contended that this was a natural motion. The aim of the tactic was straightforward: one should make
everyone feel *included*. After the shouting that had ensued just minutes prior, no one in the
audience wanted to draw the ire of the preachers by voicing their opinion. The congregation had
fallen in line.

As the street magician aims to swindle onlookers out of their money by showing them a sleight of
hand and convincing them of their certain victory when the dice is cast, a confident
self-introduction can sweep the audience off their feet through these 2 rudimentary tactics. Thus,
the preachers ended their sermon.

These tactics are controversial: many people in the world outside IIT Kharagpur[fn:1] believe that
they are absurd, counter-productive and would make one a laughing stock if adhered to!
Astonishingly, even the voice in the back of my head agrees wholeheartedly with those people. How
can such utterly opposite natures reside within my own person?

These sessions continued unabated for 6 days with more-or-less the same content. The sermon ended at
11 pm and all the second-years were tired from having to sit on the ground for more than 2 hours. On
returning to their rooms, they promptly fell asleep, mentally counting their blessings at having the
guidance of world-wise men who were willing to spend mind boggling amounts of time schooling them on
*basic* soft-skills, such as shouting at the top of your voice, choosing hobbies that were
beneficial to your hostel and why other halls did not have /that undefinable quality/ required to
win the GC[fn:3]. The drowsy second-years would remember that this valuable tutelage was not being offered
to their peers in /grossly inferior/ "hostels" such as LBS, where the seniors were shirking their
duty of conducting O.P and had the *audacity* to focus on their personal lives. These seniors were
indifferent and did not want to play a major part in valuable and meaningful endeavors such as
raising the esteem of their living quarters.

While this sermon was delivered to a congregation where participation was voluntary, more was about
to come, and future sermons would *go* where the second-year was. The Common Room was seldom
frequented by some parishioners and these people were missing out on /essential knowledge/. To
remedy this, the next part of O.P. was conducted in a place which no one could avoid: The Dining
Hall.

-----

*Programming note:* This is the second part of a 4-part series. New posts will be published at 11 am
UTC (4:30 pm India, 8 pm Japan).

| Post                                                  | Date           |
|-------------------------------------------------------+----------------|
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/10/orientation-program-iit-kharagpur-part-1/][The Curious Case of the Dweller Who Wouldn't Move Out]] | 10th May, 2021 |
| [[http://localhost:4000/iit-kgp/india/orientation-program/2021/05/11/orientation-program-iit-kharagpur-part-2/][The Sermon in the Common Room]]                         | 11th May, 2021 |
| Victorian-era Dining Hall Etiquette                   | 12th May, 2021 |
| The Midnight Assemblies                               | 13th May, 2021 |

-----

[fn:1] Apparently, there is one!

[fn:2] Why would you want to say omit or include things based on your audience?! "It's elementary,
Watson".

[fn:3] A /soft skill/ only when looked at in the /really/ big picture.
