#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Monthly Recommendations (May 2021)
categories: monthly series reading
---
#+end_export

This month, we deal with the recent past. The recommendations include the profile of a digital
marketer, which looks back at how Trump's 2016 campaign used the tools at their disposal effectively
to achieve something the /mainstream/ strongly believed was impossible, an article about the
disastrous effects of healthcare systems being optimized for efficiency and the steps we can take to
avoid them, and how loneliness might be one of those truly new and modern problems which time
travelers would be unable to explain to their relatively temporally close counterparts in the late
1700s.

#+begin_export html
<!--more-->
#+end_export

1. *The Man Behind Trump's Facebook Juggernaut (Marantz)*

	[[https://www.newyorker.com/magazine/2020/03/09/the-man-behind-trumps-facebook-juggernaut][New Yorker]] ([[https://archive.ph/LoyBJ][archived]]), March 9, 2020

	This is a profile of Brad Parscale, a digital marketer with no political experience, who worked
   on Trump's 2016 campaign and used Facebook effectively to do things that neither Facebook nor the
   mainstream thought were useful, possible or impactful enough to decide elections. He proved them
   wrong by diligently looking for the things that were possible within Facebook's tools for
   Advertisers and trying everything. Noteworthy among the strategies that he employed was one which
   required campaign event attendees to enter their phone numbers to get free tickets. This data was
   then uploaded to Facebook as a spreadsheet and Facebook used the data in their databases to
   create a list of users who were similar to campaign event attendees.

2. *What The Coronavirus Crisis Reveals About American Medicine (Mukherjee)*

	[[https://www.newyorker.com/magazine/2020/05/04/what-the-coronavirus-crisis-reveals-about-american-medicine][New Yorker]] ([[https://archive.ph/ncFxf][archived]]), May 4, 2020

	Efficient systems are great: They are the holy grail of capitalism. The inefficiently used
   resource is detrimental to your bottom line. Healthcare is not a capitalistic endeavor
   though. So, when hospitals, schools, nursing homes, and kindergartens are run using these
   principles of least resource wastage, they are less resilient to *major crises*. This article is
   not a rant; It looks *forward* in a useful way. It is not /just/ a survey of the problems that
   were in the system which lead to the disastrous outcomes in America last year; there are a lot of
   suggestions about what /we should do/. This article is focused on the American healthcare
   system. The Indian healthcare system is no different: Private players make up most of the market
   and insurance coverage is very low (in this regard, the Indian system is in a worst state than
   America, where coverage has expanded in the past decade). As India's insurance market grows and
   more people get insurance, hospitals and the government have a good opportunity to side-step [[https://youtu.be/tYrKubNUtVk][bad
   outcomes]][fn:1] in the future.

3. *The History of Loneliness (Lepore)*

	[[https://www.newyorker.com/magazine/2020/04/06/the-history-of-loneliness][New Yorker]] ([[https://archive.ph/6gckG][archived]]), April 6, 2020

	During the feudal era, loneliness was unheard of. During the Victorian era, even the wealthiest
   people had no privacy and were surrounded by housemaids and cooks who hovered around
   incessantly[fn:3]. Lepore argues that there has been a paradigm shift in society.

	#+begin_quote
Before modern times, very few human beings lived alone. Slowly, beginning not much more than a
century ago, that changed. In the United States, more than one in four people now lives alone; in
some parts of the country, especially big cities, that percentage is much higher. You can live alone
without being lonely, and you can be lonely without living alone, but the two are closely tied
together, which makes lockdowns, sheltering in place, that much harder to bear.
#+end_quote

	I am [[http://localhost:4000/take/history/covid19/2021/02/12/the-previous-year-take/][suspicious]] of phrases like "paradigm shift". Lepore does an incredible job at putting forth
   a convincing argument though. Measurable loneliness has increased in the past few years and this
   article gives the historical context which was missing from Vox' excellent video on the topic,
   [[https://www.youtube.com/watch?v=EidKI1Bdons][Why Are We So Lonely?]][fn:4].

4. *The Untold Story of How Jeff Bezos Beat the Tabloids (Stone)*

	[[https://www.bloomberg.com/news/features/2021-05-05/how-jeff-bezos-beat-the-tabloids-the-untold-story-of-money-sex-and-power][Bloomberg Businessweek]] ([[https://archive.ph/RB2Zs][archived]]), May 5, 2021

	Say you own a leading newspaper and are famous and powerful enough for people to believe you and
   go out on a limb to do favors for you. Further, say that you are hit with a scandal that
   threatens to take away some of the wind from your sail and reduce you to a mere human. What do
   you do? Jeff Bezos has written the playbook on one of the options you have: *Go on the offensive*
   and relentlessly hound the tabloids that are trying to take you down using your media
   connections. This recounting of what he did and how he succeeded is bizarre, unexpected and reads
   like a crime-thriller novel. There are a lot of names and keeping track of all the characters
   gets to be a chore though.

5. *Two Big Things You Need to Understand About Inflation (Smith)*

	[[https://www.bloomberg.com/opinion/articles/2021-05-11/debt-makes-the-fed-s-job-harder-if-inflation-accelerates][Bloomberg]] ([[https://archive.ph/wqxsJ][archived]]), May 11, 2021

	Inflationary pressures are [[https://mospi.gov.in/documents/213904/416359//CPI%20Press%20Release%20April20211620820847886.pdf/86ae651c-6756-3fab-b8b4-c30c60c22f30][on the rise]][fn:2]. Central bankers are convinced that this is a
   temporary spike and that it will subside. There is a lot of economics jargon thrown around on
   publications that are focused towards savvy readers and I don't understand any of that; so
   articles like this one clarify the situation for me, without /dumbing/ down the issue enough to
   make it boring or "obvious". Laypeople are often disconnected from economic news and seem not to
   care much about inflation unless it reaches a record-breaking number and newspapers start running
   front-page articles about it (like during India's double digit inflation period in
   [[https://tradingeconomics.com/india/inflation-cpi][2013-2014]]). But inflation plays an important role in daily life (should I buy 10 kg of rice
   before the RBI's Monetary Policy Committee releases the minutes of their meeting this Friday?)
   and for longer-term investment planning (If [[https://mospi.gov.in/][inflation]] is at 5.5% and [[https://www.sbi.co.in/web/interest-rates/interest-rates/deposit-rates][deposit interest rate]] is
   4.4%, what term length should I choose for my fixed deposit?).

-----

[fn:1] This Newslaundry video has a good interview of what happened and the workarounds that were
used by ingenious doctors and nurses to prolong their Oxygen supply. Unfortunately, the camera work
is inexplicably /shaky/. The doctor says something that is disturbing for any healthcare consumer:
"I am sitting here with narrow coronaries ... I don't know if I am supposed to be concentrating on
treatment of patients or trying to get Oxygen [using Twitter and talking to officials]".

[fn:2] See paragraph (4.) in the press release. Cost-Price Index has gone up in all places between
March 2021 and April 2021.

[fn:3] A reference from the TV show Downton Abbey and novels like The Remains of the Day (Ishiguro).

[fn:4] If you want to spend more time listening to someone talk about loneliness dispassionately,
then I recommend [[https://www.vox.com/2020/10/15/21517358/democracy-neoliberalism-predestination-loneliness-the-ezra-klein-show][Marilynne Robinson's interview]] on the Ezra Klein Show.
