#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: '"Absurd Customer Service" - Part 1, The Problem'
categories: experiences absurdity customer-service
series_id: absurd-customer-service-problem
---
#+end_export

Over a series of several occasions last year, I experienced the absurdity rife in modern customer
service. I don't think that things have always been like this. Customer service was a pain and you
would often by stuck on 30 minute phone calls trying to explain your situation to the other
person. But there *was* a person at the other end. And after those grueling 30 minutes, they *would*
understand your situation and do something to rescue you from it. My experiences did not conform to
this pattern. It looks like this problem is [[https://www.wired.com/story/phone-scam-phishing-finance-apps/][widespread enough]] to warrant feature articles in
magazines.[fn:3] Indeed, in all the cases that I encountered, the problem was eventually resolved in a
miraculous and bizarre fashion; with my interventions seemingly making no impact on the course of
things. My experiences were with multiple businesses and in different industries: telecom, banking,
and retail. But I think that there are some common trends which can be pinpointed. These trends have
made the experience of "reaching out to customer support" in India a painful and exasperating
experience. In this, the first of a 2 part series, I briefly recount my experiences. Hopefully, the
reader has not been through similar experiences and can read them simply as an amusing recounting of
events that will never happen to them.

#+begin_export html
<!--more-->
#+end_export

* Telecom

In my experience with the Telecom industry, I wanted to switch plans for a mobile phone connection
from Postpaid to Prepaid. This is a routine process and any business worth their salt will be
careful to establish a well-defined process which can be followed by all the people working at its
brick-and-mortar stores. The business in question was Airtel. Airtel is one of the largest players
in the telecom business in India and they have been around for a while. So, I did not expect any
issues at all. But despite multiple visits to a physical store, the process was simply not getting
done.

The clerks at the store had no clue about what was going on. They were sitting in front of a
computer screen and reading out the errors that were being shown to them on the screen. Indeed,
their presence was merely aesthetic as they seemed to add neither warmth nor value to the
communication I was having with the computer. All of this went up a notch when, in a burst of
frustration, I called Airtel's customer service line 121.

The menu of options is confusing, beyond belief. The main purpose of this menu seems to be to drive
the user away from the phone to the app store and to get them to install the "Airtel Thanks" mobile
application[fn:1]. Ironically, the reason I was calling the customer service line was because I had
already lodged a complaint through the mobile application. However, this complaint seems to have
disappeared into the vast ether of the universe because I could not get it in the list of complaints
on the *same* app. I did not receive any other communication about this complaint either.

On the phone, after having listened to endless automated voice guidance read out in a sooth voice
that is not at all representative of the listener's frustration and after delving through some of
the options and repeated ventures down the incorrect road, I figured out how to get to a human. The
customer service line is not staffed with many people. So, often, there are long waits before you
get connected to a human being. This wait generally lasts a few minutes, minutes that one can
productively use to contemplate the futility of their efforts in a universe that has been around for
billions of years and will continue unchanged for billions more.

At the end of this wait, I was connected to a person whose official designation /I believe/ was
"Customer Service Executive Extraordinaire Emeritus."  In typical corporate jargon fashion, this
title is meaningless and serves only to divert you from the exceptionally bad service you will soon
receive. After explaining what I wanted to achieve to the person on the other end of the line, she
told me straight away that there was nothing she could do. The only people who could help were the
people at the physical stores. So, her counsel was to simply return to the store.  /Somehow/ this
conversation would affect the scheme of things and when I next return to the store, the people there
would be able to achieve what on 3 prior excursions they had failed miserably at. I wondered if this
customer service agent is a believer in a religious sect where doing the same thing over and over
again and expecting a different result is the central tenet.

Seeing as she could not help with my original goal, I figured that I might as well lodge a complaint
about the store where the clerks seemed to be uninformed about the process and uninterested to check
the operation manual, which I am sure they ... Well, Airtel /probably/ did not issue them with a
operation manual. My naive belief was that Airtel would want to know about the bad experiences
their customers were having. What happened right after this convinced me that they did not have any
such desire.

I told her that I would like to file a complaint about an Airtel store. She asked me for the
address. I told her the address. She was unable to find it. I spelled it out. She was still unable
to find it. I sent her a pigeon that had a note tied to its legs with the secret code that she
needed to enter into her computer to find the store. I guess the pigeon reached her because she
/was/ then able to find it. Alas, this was useless. I am not exaggerating here. It was *literally*
completely useless that she had been able to find the store. To prove my point, here's the
conversation that followed:

#+begin_quote
*Me:* Yes, I would like to lodge a complaint about that store.

*Customer Service Representative:* I see. You will have to visit the store to do that.

*M:* Um ... really?

*CSR:* Yes

*M:* Well, that doesn't make sense. Can you put in a note for someone to check with the store manager
and see why the clerks there don't know the procedure and whether they can learn the new procedure?

*CSR:* We can't contact the store directly

*M:* WHAT?

*CSR:* We are unable to contact the store directly.

*M:* What do you mean?

*CSR:* We are unable to contact the store directly.

... the conversation continued in this vein for a few more lines. Then,

*CSR:* Well, if you want us to talk to the store manager, then there is an option.

*M:* Oh, what is it?

*CSR:* You can go to the store, call 121 from /your/ phone, and connect to a customer service
representative. When you are connected, you can ask someone at the store to talk directly with us.

*M:* Um, okay. Thank you. /(I guess?)/
#+end_quote

So, that's what happened. In summary, Airtel is a telecommunications business which provides mobile
connectivity to hundreds of millions of people. It has stores across the vast landscape of
India. These stores have managers and others working there. Airtel has no way of contacting the
stores directly. Indeed, there seems to be little or no contact between Airtel and the store, except
through the computers that are sitting in front of every single person at the store.

After all this, all I could do was laugh at the absurdity of what I had experienced. I felt much
like what I imagine Kierkegaard must have felt like when [[https://youtu.be/D9JCwkx558o][he said]]:

#+begin_quote
As I grew up I opened my eyes and saw the real world and I began to laugh and I have not stopped
since.
#+end_quote

*P.S.* We were able to switch the mobile number from Postpaid to Prepaid by visiting a different
store and following a procedure that we had heard about more than 3 years ago. The people at this
other store also had no idea about this procedure and did not inform us about it or that this was
the procedure to follow. Airtel's consistency is worth appreciating.

* Banking

My second experience was with the banking industry. This case was slightly more complex. When my
credit card was renewed, I was sent a new one. It was sent to my home address in India. There is no
limitation in India that the credit card /must/ be collected by the person whose name is printed on
the card. It can be collected by anyone at the household, as long as they are in the correct
address. As my family was still living at my home address, I believed that there would be no
problems in receiving the credit card. That was a huge mistake. *HUGE.*

As it turned out, this time around, the card was dispatched from the bank's central dispatching
center. It was sent via courier, which is very common. My home address is in a city and it is very
accessible. Delivery people from most courier companies come to my neighborhood daily.

After the first delivery attempt was logged as "Door locked," at a time that I had already confirmed
people /were/ indeed present at the house, I sensed that something fishy was afoot. I wish I could
say here that I was able to foresee what the problem was and fix it instantly.

While it is not uncommon for delivery people in India to fill in "Door locked" as a reason for not
delivering packages without even visiting the home where they are supposed to deliver it, it is not
common enough to be the first thing that one suspects. On further inspection of the scant details I
could get from a ghastly tracking page for this courier company (You have not heard about it.), I
realized that the contact number on the package was my mobile number; a number on which I was unable
to receive calls. My guess was that the delivery person was calling the phone number on the
package. On not being able to reach the phone number, they decided that the recipient was definitely
not at home and probably dead. So, they /understandably/ filled out "Door locked" as the reason for
not delivering the package.

First, I tried to contact the courier company's customer service. They had no phone line. (Their
website had been wiped of any mention of contact or phone numbers by a highly trained team of web
developers.) There was a single email ID which they apparently wished all their customers to contact
them on. An email to this address elicited a quick response.

#+begin_quote
*Subject:* Re: Delivery person did not come to my home (Tracking ID: [REMOVED])

Dear Sidharth,

We sincerely apologize for the inconvenience.We are forwarding this case to the team and assure you
of expeditious closure.

Along with this, we have forwarded the request to deliver the shipment on priority and will try to
deliver it at the earliest.

In addition to this, we have forwarded the alternative number([REMOVED]) to the team. Meanwhile, we
request you to contact the merchant([REMOVED]) to update the contact number.

Best Regards

[Name]
Customer Experience
[Courier Company]
#+end_quote

The content of this email was encouraging. It /sounded/ like someone had read my email, understood
my situation, and taken some action. This basic requirement of a "human response" was satisfied!
But, as the astute reader might have guessed, this was not to be. My credit card remained
undelivered.

The first package was returned to sender after 3 failed attempts due to the spurious reason "Door
Locked." The package was sent out a second time with the same courier company, and the whole dance
was repeated one more time. Realizing that my interventions were futile and could serve to only hurt
my well being, I decided to lay-off for a period of time and not say anything.

After the package was returned to sender a second time, there were no updates. The bank had
contacted me to say that they had been unable to contact me at my address. However, what they really
meant was that they had called me and I had not picked up. Curiously, the bank did not include any
information about how /I/ might contact them. Seeing as they could not reach me on my phone number,
the logical step would be to provide another means of contact. Well, logical to me. To the bank, who
knows. Maybe they believe that a person's identity should be confirmed by /only/ their ability to
answer phone calls. Perhaps they have done extensive studies and conducted multiple security audits
and concluded that while people engaging in identity theft might be able to physically impersonate
another person or enter the victim's home and receive packages on their behalf, most identity
thieves were /never/ able to answer phone calls on behalf of the victim.

In a last ditch attempt, I emailed the general customer support email address of the bank. I told
them that the delivery company they were using did not have coverage in my area and that they should
use another company. (I might as well try something new as my original story seemed to have no
traction with any Customer /Service/ Representative.) This email did not elicit a response. There
was an automated response which assigned me an incomprehensibly long "case number." I wonder why
they bother issuing these case numbers. And I wonder why these case numbers are so long. Are they
really dealing with billions of customer service cases? Is that not a sign of dysfunction in and of itself?

After a few days, one fine evening, I received an SMS on my contact number saying that the credit
card will be delivered to my home in 30 minutes by a different courier company. I had done nothing
to trigger this change in courier company. Indeed, about 30 minutes later, the package was
delivered. Here again, the bank's belief in mobile telephony was reinforced! When the person arrives
at the door to deliver your package, an SMS is sent to you with a 2-Factor Authentication code. If
you are unable to provide this code to the delivery person, you are not you. Of course, it follows
that if you are able to provide this code, you *must* be the intended receiver. *Why believe in
government documents that establish your ID when you have a mobile phone capable of receiving text
messages?*

* Retail

My final set of examples is from retail. It is a well known fact that retail jobs are the worst of
the bunch because store clerks have to often deal with adults without /emotional regulation,/ prone
to fits at the register, offloading on the poor person standing behind the register. So, my empathy
for people in these jobs is quite high. However, the capitalist machinations operate these people
have made them do some very strange things.

The first instance was at a cafe inside a mall. After buying something, I went to the register to
pay. There the clerk told me that they did not accept cash; that they accepted /only/ credit or
debit cards. While the inverse of this is something that most people might have experienced, I had
never experienced anything like this. After a few seconds of being surprised by this strange
request, I told him that I did not have a card of any sort and that cash was all I had. At this
point, another person working at the cafe came to his side, and they conferred briefly. After this,
he said that he would be happy to accept cash and opened the register. *What do I see inside the
register but ... paper money?!?!* Why did the people who run this cafe start this absurd campaign to
accept anything but cash, when their register was clearly stocked and cash is recognized legal
tender across the country? I can not say; I can not even imagine a case in which this would make
sense. Maybe they /like/ to pay the 3% service charge that companies like Visa and MasterCard charge
for the trouble of facilitating credit cards and operating a large network.

The second instance of retail absurdity is really many instances of the same experience. Whenever
you buy /anything/ and go to pay for it, the likelihood of being asked for your mobile number is
high. I think, in current day metropolitan India, it is basically 100%. Across a wide variety of
shops selling clothes, footwear, and food, I was asked for my phone number at almost every
turn. Being rather adamant about not sharing my phone number, I have caused lines to form behind me
as I try to convince the person at the register that I don't want another random human being to have
to call me and tell me about the availability of money that I will never borrow or insurance that I
will never buy. I explain to them how it will waste both of our times and how the activity of
entering my phone number into the computer screen wastes the cashier's time.

This phone number requirement in daily life has reached absurd proportions now. On a recent trip to
a mall parking lot, the age-old parking slip had been replaced by ... you guessed it ... a mobile
number. Every vehicle parked inside the parking lot /did/ have a registration number. But once
again, *the mobile phone seems to have superseded the vehicle's unique registration number as an
identifier for the vehicle!* Absurdly enough, the phone number was collected at entry and at exit by
a person. It was not used to speed up the process or reduce the number of people who staffed the
parking lot. I tried to provide the person with an arbitrary mobile number. This worked, so long as
I remembered the mobile number when I exited the parking lot. So, the question I had after the
experience was, *why change something which gives you neither a monetary benefit nor an improved
experience?*[fn:2] Well, perhaps, customer service absurdity has warped the minds of executives at
the top of these companies enough that they don't even recognize that they are inside a capitalist
society anymore.

-----

[fn:2] I am being frivolous here by suggesting that the collection of mobile numbers does not have
monetary benefits. There are reports of companies which build up databases of names and phone
numbers and sell them to cold calling firms which will use the database to sell loans / products
etc. Surely, the mall earns more from the patronage of a returning customer than from selling a
phone number database?

[fn:1] That is the real name of the app.

[fn:3] A cursory search for this problem lead me to [[https://www.forbes.com/sites/jeffbevis/2019/05/16/the-decline-of-customer-service-in-america/?sh=4bb5d2a92fde][this article from 2019]] that tries to persuade
businesses to use technology to connect customers with humans, rather than with computers.
