#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Gaslit on Twitter
categories: twitter social-media information
---
#+end_export

Gaslighting is a catch-all term. I understand it as the act of relentlessly bombarding a consumer of
information with a large amount of irrelevant statistics and facts to such an extent that the victim
can no longer convincingly explain (even to themselves) their fundamental beliefs. There is a lot of
talk of "gaslighting" in media environments where there is a single source of news. In India,
nightly news shows are a great example. It is also relevant in environments where a news source is
seen as biased. The biased news source' reporting is criticized using a bunch of unrelated facts.

On the 28th and 29th of March 2022, there was a 2-day strike call in India. This news was reported
by the New York Times, and crucially, it was included in the "Daily Briefing" newsletter's Asia
edition on [[https://www.nytimes.com/2022/03/28/briefing/biden-russia-oscars-will-smith-israel.html][28th March, 2022]][fn:1]. I had not heard about the strike. (Not surprising, as I don't
live in India and have been more out of the loop than usual lately.) None of the people I know in
India mentioned it to me over the previous weekend. When I read about the strike, I did *not* think
that NYT was reporting a lie. I accepted it as fact and went to a few Indian news websites to read
more about the strike. Quickly, I started questioning what was going on and why real people (not
"trolls") were saying absurd things online. I am not the first person to go through this
disorienting experience and I won't be the last. I want to talk about why I felt disoriented, how I
battled with this feeling, and how I managed to resolve my disorientation by doing some research.

#+begin_export html
<!--more-->
#+end_export

* Part 1: Is It True?

#+begin_quote
There is nothing quite so humiliating and disempowering as trying to prove the truth.
-- [[https://youtu.be/nknYtlOvaQ0?t=348][Masha Gessen on "Why obvious lies make great propaganda"]]
#+end_quote

I started scrounging around the websites of some well-known Indian news websites. I checked the
website homepages for NDTV and Times of India. These two did not have any mention of the strike on
the homepage. A 2-day strike call across all of India is a *big deal.* It can potentially shut
down the economy completely and significantly affect people's lives.

(*For e.g.* Banking and public transport unions had called for a strike. This could have affected
anyone who was planning to take a bus to the train station on one of those two days or was planning
to withdraw cash from a bank for a crucial purpose such as the purchase of a home or jewelry.[fn:2])

This is *very* newsworthy. /Even/ if these news organizations had information which suggested that
the strike's effects would be limited, /this/ is front page news. Not being able to find the word
"strike" on the NDTV homepage is confusing.

After a few minutes of searching around for the terms using a search engine, and specifically the
query =site:ndtv.com india strike=, I saw that the strike was very much real and happening across
India. It was being covered by both the news organization whose home page I had checked; However,
the links to these specific pages were not included on the homepage. So, the only way to reach these
pages was from an external search engine.

I had confirmed that the strike was indeed happening. To find out more about its immediate effects,
I went to Twitter. I was hoping to find some people who were as stunned as me by the (ostensibly
deliberate) under-reporting of this story. At the very least, I wanted to find some users
complaining about or reporting some of the disruptions caused by the strike. I *did not* find that.

* Part 2: Here's The Thing About Twitter

Twitter is not very relevant when it comes to learning about what Indians are thinking.  Looking at
just the raw numbers, it becomes apparent that a very small percentage of the total population is on
Twitter.

| Statistic                                        | Count        | Percentage of Population |
|--------------------------------------------------+--------------+--------------------------|
| India's population[fn:3]                        | 1.40 billion |                     100% |
| Number of people on the Internet in India[fn:4] | 624 million  |                    44.5% |
| Number of people on Twitter[fn:5]                | 34 million   |                    2.43% |

2.43% need not necessarily be unrepresentative. But clearly, the exclusion of nearly half the
population that does not have access to the internet makes the sample of users on Twitter an
unrepresentative sample of the population.[fn:6]

There are some other biases when it comes to the segment of the population that is on
Twitter. Namely, they are almost certainly literate and at least partially proficient in
English. (This last assumption might not hold true for much longer, as Twitter seems to be branching
out into regional languages.) These add up to a good assumption that most people on Twitter are not
using public transport daily (either because they can afford taxis, have private transport, or do
not need to go anywhere on a daily basis because they are working-from-home) and that they probably
never go to brick-and-mortar bank branches, doing most of their banking online. So, their opinions
about a strike which would affect these two segments of daily life are of little value.

Nevertheless, I went to Twitter because this is also the only platform where open discussion is
possible, except for group chats that one is a part of. These group chats are generally echo
chambers and seldom contain opinions that I forcefully disagree with.

On Twitter, I did not find reaffirmations of my belief that this story was being
under-reported. Quite the contrary.

It became clear soon enough that a New York Times tweet, one that mentioned the article about the
strike in India, had become a flashpoint for all strike-related conversation on Twitter.

#+begin_quote
A two-day nationwide strike in India, involving both public and private sector workers, has
disrupted transport and other services across the country.

Workers are protesting the government’s economic policies, including a privatization plan.

[[https://www.nytimes.com/2022/03/28/world/asia/india-modi-general-strike.html?smtyp=cur&smid=tw-nytimes][General Strike Throws India Into Confusion]]

-- [[https://twitter.com/nytimes/status/1508414880579211277][Twitter]] (March 28, 2022)
#+end_quote

Around this tweet, there was much derision targeted at the NYT.[fn:7]

#+begin_quote
Really ! When did this happen in my country ? Guys stop googling to write news , be on ground to
write news.

-- Twitter
#+end_quote
# https://twitter.com/iamneel0601/status/1508983473427853312

There were some attempts at humor. But the meat of the derision clarified the biases of the
population that is on Twitter.

Cars on the roads? There can not possibly be a strike of any kind.

#+begin_quote
Take a look at Kolkata today buddy. Wipe your eyes once again.

-- Twitter
#+end_quote

#+begin_quote
Traffic in Kalyan

-- Twitter
#+end_quote

Offices and shops open? There can not possibly be a strike of any kind.

#+begin_quote
Business as usual, shops are open, so are offices. Roads are jam-packed with vehicles.

Where is this so called bandh?

-- Twitter
#+end_quote

Why was I wading through all this? To find some mention of whether public transport and banking
services were open, as the strike was targeting only those. One user reported that buses in Mumbai
were on the road and plying as usual. This is the kind of useful discussion starter that I was
expecting on the platform.

#+begin_quote
Where is the strike ? My kids went to school and are back . Even my maid came to work by BEST

-- Twitter
#+end_quote

Most of the tweets were just derisive towards the NYT; some mentioned articles about media biases
against Asian and other lower-income countries; or about how the NYT did not have a reporting team
in India and did not know what was going on on-the-ground. No one was engaged in any kind of /real/
fact-finding about the strike and whether it was affecting /someone else./ Indeed, the
self-centered-ness of some of these users is quite shocking.

* Part 3: What Happened?

Reporting from the strike clarifies its impact. Here's a catalog of the impacts with the relevant
sources.

Banking services were affected nationally.

#+begin_quote
"As per our reports, in the Southern Grid functioning in Chennai, during our strike yesterday and
today, about 6 lakh cheques/instruments worth about INR 5,000 crore could not be sent for clearance as
branches did not function due to the strike," All India Bank Employees Association (AIBEA) general
secretary CH Venkatachalam said.

At the national level, about 20 lakh cheques worth about INR 18,000 crore could not be cleared, he
claimed[fn:8].
#+end_quote

The informal sector and small-scale industries were not impacted.

#+begin_quote
However, the Confederation of All India Traders (CAIT) said the strike called by a joint forum of
trade unions has been a "total flop" in the informal sector.

In a statement, it also claimed there was no impact visible even in various industrial areas where
small industries are having manufacturing activities[fn:9].
#+end_quote

Kerala, a Southern state in India, seems to have been worst affected. This is not surprising;
decades of [[https://en.wikipedia.org/wiki/Communist_Party_of_India_(Marxist)#Kerala_2][CPI(M)]] rule in Kerala have created strong trade unions in the state. The same is true in
West Bengal, where the [[https://en.wikipedia.org/wiki/Left_Front_(West_Bengal)][Left Front]] was in power for 35 consecutive years between 1977
and 2011. (There is a common joke about West Bengal and strikes.)

#+begin_quote
State-run KSRTC buses did not operate while taxis, auto-rickshaws and private buses kept away from
the roads across the state. Commercial vehicles including trucks and lorries are also not running
expressing solidarity with the strike.

However, the essential services including milk, newspapers, hospitals, ambulances were not
affected.[fn:10]
#+end_quote

Participation seems to have been significantly lower than the expected 200 million formal and
informal workers that the unions were expecting.

#+begin_quote
Amarjeet Kaur, All Indian Trade Union Congress General Secretary, told PTI that they are expecting
participation of over 20 crore formal and informal workers with mass mobilisation of workers across
the country.[fn:11]
#+end_quote

-----

*Here's what happened:* A bunch of trade unions issued a strike notice to nearly 200 million workers
across India. This notice was reported upon by various news organizations within and outside
India. This reporting did not have any unusual bias in favor or against India. The strike notice was
not as effective as the unions initially expected. The strike's impact was felt by a segment of the
population, especially those in the states where unions are strong and the history of strikes is
long. However, the people online who were sharing their opinion and experiences on Twitter were
mostly unaffected by the strike. This lead to a belief that there was no strike and that reporting
was reflecting the foreign media's anti-India bias. These people did not take any effort to confirm
whether the anecdotal evidence they had at hand was representative of other population
segments. Once people started railing on NYT, Twitter became an echo chamber where no other opinion
could break through. Once this pattern took hold, the story was no longer "Strike notice not as
effective as unions initially predicted." It became: [[https://www.msn.com/en-in/video/watch/nyt-misleads-readers-about-india-strike-article-s-title-blows-the-strike-out-of-proportion/vi-AAVDoz3]["NYT blows strike in India out of proportion."]]

* Footnotes

[fn:1] I could not find the number of users who read this briefing.

[fn:2] India's ATM withdrawal rules are strict and do not allow withdrawals of more than Rs. 25,000
per day.

[fn:3] [[https://www.worldometers.info/world-population/india-population/][India Population (Live) (Extrapolated from UN data) (Worldometers)]]

[fn:4] [[https://www.statista.com/topics/2157/internet-usage-in-india/#topicHeader__wrapper][Internet usage in India (Statista)]]

[fn:5] [[https://www.statista.com/statistics/381832/twitter-users-india/][Number of Twitter users in India from 2013 to 2019 (Statista)]]

[fn:6] By comparison, in the US, [[https://www.statista.com/statistics/265647/share-of-us-internet-users-who-use-twitter-by-age-group/][68 million people are on Twitter]] (20.5% of the population) and in
Japan, [[https://www.statista.com/statistics/381839/twitter-users-japan/][26 million people are estimated to be on Twitter]] (20.8% of the population).

[fn:7] Going forward, I mention the text of a few tweets. However, I have decided not to publish the
links to these tweets in this blog post.

[fn:8] [[https://www.ndtv.com/india-news/banking-services-impacted-on-second-day-of-nationwide-strike-2849354][Banking Services Impacted On Second Day Of Nationwide Strike]]

[fn:9] [[https://www.ndtv.com/business/nationwide-strike-hits-banking-operations-public-transport-services-2848273][Nationwide Strike Hits Banking Operations, Transport Services]]

[fn:10] [[https://www.ndtv.com/india-news/two-day-strike-affects-normal-life-in-kerala-2847129][Two-Day Strike Affects Normal Life in Kerala]]

[fn:11] [[https://www.ndtv.com/india-news/bharat-bandh-bank-strike-called-on-monday-tuesday-your-10-point-guide-to-march-28-march-29-workers-protest-2846165][Trade Unions Call For Bharat Bandh Today, Tomorrow: Your 10-Point Guide]]

# Twitter URLs
# List of URLs for the Tweets included in this post are also included in this post as GPG encrypted
# ciphertext.
# Encryption: cat urls | gpg --armor -r mail@siddharthkannan.in --encrypt -
# Decryption: cat urls.gpg | gpg --decrypt
# Key: 665AB164DEC670A3
#
# GPG ciphertext:
#
#    -----BEGIN PGP MESSAGE-----
#
#    hQGMA2ZasWTexnCjAQwAnQ37AkLPOkMl+ILrjNnozHnKO3ZBWIZSAdoBVUiY/3AR
#    8fz0QVf4NLcyZgDP4/3GJDejfxqOxdK7oUp7cd4RipOmBk0GMVe4kua9lynEu/zP
#    2v1P4/KSm9+BttCOTtFxzJLuC3aJFQQ7fFwKecKfkCdi1SnaaYz8709bMZ0TNq3a
#    pfn0lo7EpTwIw61io9ONPqkGbiHqpNIuNanY5ogLOniyR/aUERg6iYguxc5WepGM
#    rVu5wt/GH2YXRoT2JTieDNI3nzF7Hx78+2FCGFmn8iuGGrAq4KdlByTBf+AO5/nK
#    Jw+SktBoT9AqMEWX9VlFsdEJ4/KcnXAkoao6XgbjFbRbxR8QEwaHhrtF+k2UxGuu
#    CsPXc3gDi8JQkaSBRXno1f78we7Ae77p2crQQENrXgcCvznsVBuE0GM0uSomKmK/
#    Q4pa1vp93+sbEczDfKrtCRoHrFO+lCpq3ruCsoIR4IYv8mDhBG+DBRUfNcZNzAMU
#    RCDAa9D3eDz1+MpJK67g0sAaAQfz+0gUU+9viz5DyKuT6CsVtkUwSLr2pwuVMkeW
#    q3pwNdC9Amx9yR7H9SSkKQ4pyNi3y8wSJ+rbMjwo1JCcDj0z7X+HFDy4pjxsSao1
#    5gMmsIzorL1tctpcDX4rQjLOlFX5O0pShjXeDu1R1hV+AMiavhMLQehjBJgyaLAe
#    IyffJBE5UeDSeOdZRmsIKwYL6cxLbCbu95UXxP3wYH0FczPHnm5VlrQe1fJWTgyl
#    jyGXeeKSEOG2rzbwtIbWvXo1Vy0f2WWK/qWQUc+YP0Pzk4x4J0oxvss3xsk=
#    =XZMG
#    -----END PGP MESSAGE-----
