#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Video Calls Are Tiring
categories: covid19 video-calls skype
---
#+end_export

Video calls are ubiquitous. Skype and its modern counterparts were the go-to tool for connecting
people who were not in the same physical space. In the era when travel was possible, convenient, and
exciting[fn:1], these tools were stopgap solutions; to be employed /until the time that/ you could
refill your "physical presence" account balance with people. Then, COVID19. Everyone was stuck at
home. Travel became impossible. Video calls became the only way to meet some people. At work, the
number of people that I interact with on a daily basis whom I have never met in real life has gone
up from 0 in March 2020 to 5 this past week. I don't think my experience is an outlier. The
necessity of using this tool could not be escaped; neither could the feeling of tiredness that would
always follow its use. What is the source of this tiredness?

#+begin_export html
<!--more-->
#+end_export

The fundamental characteristics of a video call have remained depressingly constant since the
initial days of Skype: a small rectangle with your face and a large rectangle with the other
person's face. Consider this quote from a 2011 article in the New York Times:

#+begin_quote
But the disconcerting thing, he said -- as others have mentioned -- is that the current technology
means one is rarely looking eye to eye. "When someone doesn't look us in the eye, the brain deduces
this as someone being less likable, less confident and less honest"
-- https://www.nytimes.com/2011/05/21/your-money/21shortcuts.html
#+end_quote

As it happens, the "current technology" of today, 2022, still does *not* let you look eye-to-eye. To
exacerbate the problem, there has been a wild expansion of the primary use-case, "establishing
business relationships," which was being considered in 2011.

Video calls replaced every activity that called for congregation: work, school, happy hour, dance
classes. They are *a poor replacement* for congregation; no one is on that side of the debate
anymore. Conversations about video calls replacing in-person meetings were in vogue in 2011, and
they were in vogue early in the pandemic, when work-from-home was reducing work travel and giving an
unprecedented amount of flexibility to employees.

Adults might be surprisingly good at using these tools for work. Children are not doing well using
them for school. I will repeat the oft-repeated truism: "Video calls lack the /human touch/." Every
uttered sentence is quickly transformed into a cold, emotionless gob of words, devoid of facial
expressions and hand gestures, making the communication of a simply sentiment tortuously hard.

It was the /best worst solution/ for the problem that faced /almost/ everyone. But people in jobs
that involved meeting people for 8 hours a day noticed early on that *they were tired* after meeting
a lot of people online. And more so than they would have been had they been meeting the same people
in person. I felt the same way during the workdays when I had meetings for several hours at a
stretch.[fn:2]

The initial explanation of this tired feeling was external to the primary communication tool. The
blamed was pinned on other plausible sources of anxiety: the news cycle was crazy and we were
bombarded with depressing information (China, Italy, New York, ...); spaces at home were not
designed to be conducive to a comfortable work day anyway; we /just/ did not have the right
equipment, and other arguments in this vein. This went on for some time. However, these explanations
were not enough. People were tired and the reasons had nothing to do with external factors. They
started looking within and at the tools that they had taken for granted until then.

There was soon an explanation that involved *performance anxiety:* online performers and live
streamers who had been broadcasting for a long time said that *all* video calls are performances and
everyone is on a stage. Moreover, this online stage is worse than a physical stage because it is
equipped with a mirror which shows you what you look like.[fn:4]

This explanation made sense to me. Even though I did not think of video calls as a performance, I
saw that I was transfixed by the small rectangle that I was broadcasting. This small rectangle had
no new information; I should not have been looking at it at all. Nevertheless, it was the natural
resting place for my vision on the screen and I kept returning to it every few seconds.

To this explanation of performance anxiety, I want to add 2 supplementary points. I believe that
these exacerbate our anxiety and self-consciousness, and make our experience of video calls
unnatural and tiring.

* Strange Proportions

First, the unnatural size of the opposite person. My phone screen is 5 inches tall and 3 inches
wide. The average human face is approximately [[https://www.reference.com/science/average-size-human-head-62364d028e431bf3][10 inches tall and 7 inches wide]]. To deal with this
problematic difference in proportions, wide-angle cameras take to cropping the feed
appropriately. This gives rise to a mash-up of strange proportions.

If the speaker is sitting too far off, a small face surrounded by empty space. And if the speaker is
holding the phone too close, an impossibly large face that takes up the whole screen. There is no
way to win. I noticed that I always ended up with a video feed which is great for the first few
minutes of a conversation when I was assessing it with curiosity. As the conversation continued and
I focused on what the speaker was saying rather than where they were or what they were up to, the
strange proportions became unavoidable.

There are recommendations to fix this: "Keep the camera fixed. It should line up with your line of
sight.  Sit in a chair at a comfortable distance from the screen." This advice is easy to follow
when you are at work inside your house. But when you are on a video call with family, it is hard to
stay in a single place and maintain unchanged posture for long periods at a stretch.

* Expectation to Not Look Away from the Screen

Looking away from the screen *during* a video call is taboo. When meeting someone for the first time
at work, I will tell them that I am looking away from the camera because I am writing on a notebook
in front of me and /not/ because I am being rude. The expectation to not look away is strong. It is
a sign of politeness online, where the other person can't see what you are staring at off-camera. My
assumption is that the other person will assume the worst thing about an innocuous off-camera look:
namely, that I am reading a tabloid article on my phone!

In real life, we rarely stare at another person's face for a long period of time. Even when two
people are talking, there are often things around them and looking at these things for a brief
moment or moving your head around is a natural way to break up the monotony of an unchanging
physical stance.

This realization came to me through Japanese lessons. When the lessons were conducted in real-life,
I rarely looked at my instructor's face when I was working on assignments or answering questions. I
would spend most of the time looking at blank walls, trying to come up with the vocabulary or the
grammar for describing a particular situation.

When the lessons shifted online, there was no expectation (either my own or my instructor's) that I
would stare at the screen/camera because I had never done that before. During these online lessons,
I would often stare outside a window to my left or at the wall to my right. These 1-hour lessons
were not as tiring as similar one-on-one meetings at work.

Eventually, unbeknownst to myself, I started applying the same tactics during my one-on-one meetings
too. Through this exercise, I consciously weakened the expectation that I wouldn't look
away. Looking at your surroundings is a part of being natural offline. There is no reason there
should be any expectation that we are stiff and monotonous online.

Video conferencing software will often put the "shared screen" of the other person front-and-center
and hide the person's face in a sidebar. Google Meet used to do this by default before. If both
people are staring at the shared document, they are not staring at each other's faces. This is a
good start, however it is not a sufficient solution because the underlying expectation about not
looking away from the screen is just as strong as before.

* Conclusion

This tiredness was coined early in the pandemic: *Zoom fatigue.* Technology philosopher [[https://theconvivialsociety.substack.com/p/a-theory-of-zoom-fatigue][L M Sacasas]]
theorizes that Zoom fatigue is related to the way we perceive each other's bodies on a video call. A
video call /pretends/ to be equivalent to a physical meeting, despite being a terrible imitation:
there is neither the comforting, shared physical space as in real-life conversations, or the
intentional disembodiment of the telephone. The physical cues that our evolutionary history has
trained us to look for are expected, but missing. Video calls are good for communication, but they
are decidedly bad for people.[fn:3]

Zoom fatigue does not have [[https://news.stanford.edu/2021/02/23/four-causes-zoom-fatigue-solutions/][a simple solution]]. One solution is to stick to the "intentional
disembodiment of the telephone." A better solution is to start by sharing video and subsequently,
switching to only audio.  (It is hard to get the timing right.) The solution that I prefer is to cut
through the pretense that video calls are *"real-life conversations with caveats."* If we start
thinking about them as *"telephone conversations with a few perks,"* video calls will be less tiring
and more enjoyable.

-----

[fn:4] Google Meet implemented a feature which would fix this problem: It allowed people to hide the
video feed that they were streaming. This feature is not persistent, i.e. you have to hide your feed
in every video call, which can get tiring in itself. Other applications such as WhatsApp and
Facetime which are more commonly used in family settings don't have any such feature yet.

[fn:3] Paraphrased from Sacasas' [[https://theconvivialsociety.substack.com/p/a-theory-of-zoom-fatigue][blog post about Zoom Fatigue]]

[fn:2] Being at a company where I was not required to turn on my camera for all meetings, I
resorted to turning my camera off and pacing around the room whenever I could.

[fn:1] ... and not ridden with the anxiety of getting an RT-PCR test result
in a foreign country.
