#+TITLE: Most Valuable Resource

A few days ago, I started thinking about why I was not spending time writing posts for this blog OR
working on a side project that I have wanted to work on for a while. My conclusion was that I was
not allocating my time properly. This is not original; I didn't think it was a significant
conclusion at first. As I started working on that, I came across another question that felt like a
pretty good summary of what I was feeling at that point in time:

*What is the Most Valuable Resource in your life right now?*

<!--more-->

I started thinking about this off-and-on, and I eventually came to the conclusion that right now, it
is *Time*. Thinking back to my childhood or my time in college, and I realized that my MVR in those
stages of life were different from what it is now. In college, it was *Experience*. In school, it
was *Identity*. This post is an exploration of my thinking on this subject. It is meant to stimulate
readers to think about what their MVR is, how it has changed over the years, and how they might go
about gaining more of their MVR through conscious changes in behavior.

* High School: *Identity*

Writing about finding one's identity in high school is not very interesting or useful. The
discovering of one's identity in the world, in relation to all the other kinds of archetypes, is a
major part of one's life. I think there's some debate about when exactly one knows who they are and
are able to accept and make peace with it.

When I was in my preteens, I had my first few experiences of being _betrayed_ by the people around
me that I had considered to be friends. I don't remember the actual betrayals or _how egregious_
they were anymore. My 13 year old self would vehemently claim that it was an injustice that one
couldn't simply understand, "It is what you live it". Around this period, as I was trying to
understand why people did these things, my parents would tell me often, and forcefully, that one
must be ready to deal with people who are unlike anything that one was raised to be. This simple
piece of off-hand advice has proven very useful, as I have read more about the thought process,
conflict, political opinions and persuasion.

As I moved into high-school, I embraced the *identity* of *a studious, mathematics nerd*. I
installed Linux Mint on the desktop computer that was in our home, and waited with bated breath for
the progress bar on the screen to reach 100%. I was waiting to find out if I had effectively
prevented my parents from using the computer through the weekend, while I figured out what had gone
wrong, and tried to fix it by reading help web pages on my Dad's work computer. Or, if I had
successfully installed an OS alongside Windows. My initial installations were dual boot
installations where Mint was installed inside Windows as a simple program. As I gained more
confidence, I started installing, uninstalling and re-installing various Linux distributions in an
effort to somehow get to a "not particularly nerve-wracking" installation experience. I did not
succeed. (These days, I get around this by never removing any installation of Linux, from any
computer that I am using; a rather unappealing cop-out)

This initial exposure to Linux built a familiarity with the command line from a fairly young age. I
started using Git with absolutely no understanding of what it was really for back in 2011. None of
these things were particularly big leaps in my search for an Identity, but they all added up to
something very concrete: I was not uncomfortable having interests that others didn't share, I was
not really worried about _conforming_, I was not worried about appearing uninterested in the
"elementary" computer science class, as I corresponded with my CS teacher, via e-mail, trying to
understand how I could use languages other than C, and what she thought would be useful "Next
Steps".

(_Editorial note:_ Reading this now, I am worried that I thought of myself as too much of a
_non-conformist_, when I was absolutely not anything like that. I had good grades throughout all my
school years, and complaints from teachers to parents about me in school were never about not
conforming or question my teachers.)

This self-identification as a math nerd stuck to me as I moved into the new environment of a
coaching class with younger, more approachable "professors" and a group of extremely motivated peers
who were focused exclusively on understanding the material and performing at the competitive,
university entrance exams.

Going into college, it continued to held sway. In college, I gravitated towards courses in the
Mathematics Department, even though my major was in Mechanical Engineering, a discipline that I
never came around to fully _like_. Eventually, I ended 5 years of college with a minor in
Mathematics and Computing, consisting of courses on the Foundations of Cryptography, Modern Algebra
and Graph Theory.

(_Editorial note:_ I had to look at my transcript to remember the name of the Algebra course)

During this period, I was mostly reading fiction and I don't remember anything that I came across
that stuck with me for a long time. Looking back, these 2 quotes about studying for examinations and
performing at school and other academic settings seem apt.

#+begin_quote
Don't try to be at the top of the class. Don't be at the bottom either. Find the 85% scoring sweet
spot where you know the material well enough that you are spending the least fraction of your time
on mandatory schoolwork. Spend all the remaining time on things that you want to do.

#+end_quote

#+begin_quote
People care about your grades only when they are bad.

#+end_quote

(The first quote is from a very famous essay about preparing for exams. I have read this essay a
couple times now, but I can't find it right now. If I find it later, I will edit this post and put a
link here)

* College: *Experience*

I studied in Kharagpur, West Bengal in India. Kharagpur is a mid-sized town and is located a 2-hour
drive or a 3-hour train ride away from Kolkata, one of the four major metropolitan cities in
India. Until this point, I had lived in an industrial township near Mumbai and then in Navi Mumbai
proper, so my experience until then was very much of a bustling metro city with a wide variety of
things to do (like going to a movie theater with my friends after school exams).

Kharagpur is a great college town. The college's campus is a physical gated town within a town. One
ventures out more and more often as one gets used to living in the town. In my final 2 years on the
campus, I left the campus to go to the spots around Kharagpur town (restaurants and such) more than the
3 years before that combined.

While this sounds like a good set-up (and it was), I craved *Experience*. In particular, I craved
the experience of *foreign travel*. I was hooked to Casey Neistat's videos about his life as a
traveling Ad film-maker. I left India for the first time a few days after my twenty second birthday,
on a trip to Bali with a friend. This trip was memorable and surprisingly unremarkable. I had
incorrectly believed that my first trip abroad will be set in stone, and end up defining all my
trips after that. This was not the case, and my mind moved along much faster than I had originally
imagined it would.

There are two quotes from this period of time in life that really resonated with me right after I
had achieved my goal.

#+begin_quote
The greatest things that happen to a human being will happen to you too; you just have to lower your
expectations

-- Phil Dunphy (Modern Family) (A fictional character)
#+end_quote

#+begin_quote
You will get everything that you want in life; but it will take just a little bit longer than you
expect it to.

-- Casey Neistat
#+end_quote

* Now: *Time*

Now, I have a full-time job as a Software Engineer. I live in a foreign country, I am studying a
foreign language. The resource that has become my MVR is *Time*.

#+begin_quote
Don't say "You don't have time to do X". You _did_ have time. You decided to do something other than
X in that time.
#+end_quote

I noticed this feeling of reduction of time early this year when I started working from home. My
commute was an hour long, so one of the first immediate consequences I expected was an increase of 2
hours per day in my daily routine. This didn't happen.

After 2 months, I realized that this was not happening and I looked closely at my work hours and
found that they had not increased significantly (They had increased slightly compared to before, but
certainly not by 2 hours a day). My sleep patterns were unchanged according to my Fitbit data. I was
sleeping the same amount of time, and I was mostly adhering to a routine that allowed me to get off
of work around 7 pm.

I started focusing in on this block of time after 7 pm. I was going to sleep every day around
midnight, or later. That was a solid 5+ hours that I was using to do something other than read
books, write emails and essays, and cooking or cleaning. The culprit was Netflix and other on-demand
video sites. I found this anecdotally, and quantified it by looking at the amount of texts that I
was sending my friends about new Netflix series that I had started watching. This was a non-issue
when I had a commute as I was tired by the time I got back home and I rarely watched new shows.

For a period of time, I didn't think this was particularly concerning or noteworthy. I was watching
Netflix voluntarily and I knew that I could break the habit off if I needed to. I had also come
across some really good series like Ozark and Parks and Recreation.

As I started preparing for a proficiency test for Japanese, I started reading Japanese novels. These
books were extremely difficult to read and they often took over 16-20 hours each weekend. For my
first few novels, I spent every waking minute during those weekends that I was not cooking, cleaning
or eating, reading the novel. This was a very rewarding experience.

From here, I started thinking about cutting down on on-demand video through out-of-band solutions
(out-of-band = things other than canceling my Netflix subscription). A solution that I have been
running as a trial for the past 14 days is a "no-browser-after-10pm" policy. Today was the 14th day
of the trial, and I have decided to extend the trial for another 14 days as I have not noticed any
adverse effects from not being able to use a browser (Firefox) for the last few hours of each day.

* Caveats

A keen reader may have noticed that I didn't mention *Money* as an MVR at any stage in life. This
has been a great stroke of luck, and I have been incredibly fortunate to have not had to consider
*Money* my MVR at any point in time.

This concept is something I came up with off-hand, along the lines of the "Most Valuable Product"
(MVP) culture, that is common in some software engineering teams and companies.
