#+TITLE: What's Great about Newsroom, the TV show?
#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: What's Great about Newsroom, the TV show?
categories: newsroom tv-shows
---
#+end_export

3 months ago, I had *absolutely* no idea that people found Sorkin's writing annoying. Then, I heard
that someone I knew had given up on watching Newsroom after watching the first few minutes of the
Pilot episode. Hearing about that sent me for a brief whirl while I figured out what I liked about
Sorkin and why. I *think* now I have a better understanding of that. I recently re-watched Sorkin's
Newsroom. Watching it again after a few years since the last time I watched it, I noticed that I was
familiar with a lot more people in the show (BJ Novak from The Office, Clea DuVall and Sarah
Sutherland from Veep). I also realized that the show is packed with information, nuance and
characters who *know* what they are talking about. *Why can you only either "love" the show or
"dislike" it passionately?*

#+begin_export html
<!--more-->
#+end_export

People have talked about Newsroom endlessly. This [[https://www.newyorker.com/culture/culture-desk/in-defense-of-aaron-sorkins-the-newsroom][positive]] and [[https://www.newyorker.com/magazine/2012/06/25/broken-news][negative]] review of the TV show in The
New Yorker cover all the bases. They are both talking about the same components of the show: the
characters speaking articulately, with absolute confidence in what they are saying; each character
being good at what they do and Sorkin's ability to show the audience that this is how the system is
*supposed* to work. The critics who don't like the show find it unrealistic, annoying and
heavy-handed. Let's look at each of those adjectives in turn.

First off, let us do away with the "This is not how real people talk" critique. Sorkin is not going
for realism; all of his work has been about people speaking in ways that are dramatized, that appear
real but are very far from reality.

The reason I dismiss this critique out of hand is that I don't believe TV shows or movies need to
show reality as is. The shows and movies I like don't reflect reality at all: Contagion (2011) was
about a pandemic that ended abruptly with a vaccine; The Office (US) is a show about an office that
continues to survive despite the disastrous decision making that goes on inside it; Veep (HBO) is
about an incompetent vice president and her incompetent team reaching the highest levels of
government; Homeland is about a CIA agent who engages in espionage and commits a series of
increasingly questionable actions in pursuit of her goal. These shows *do not aim to portray
reality* at all. In my mind, the demarcation is clear: Documentaries are about reality, TV shows and
movies are *dramatized versions of reality* or an interpretation of what an "ideal" or "comically
untenable" version of reality would look like. If the critics who are negative about Newsroom are
doing it because it's not "real" enough, how would they rate any of these other shows? How would
they critique anything other than a documentary and fantasy? *Here's my question:* Is a TV show's
portrayal of events and their closeness to reality important to you?

What about the critics who say that this kind of writing is *"annoying"*? I believe I understand the
reason that people find it annoying. One of the supporting characters on Newsroom, Sloan Sabbith
(played by Lisa Munn) is a great example of a character that people find annoying. She is an
extremely well-educated economist with a Post Doctorate, who has a ton of experience and knows
exactly what she's talking about every single time she talks about anything technical. She's also
"likable" (in a sense) because she is socially inept, aloof and talks about not having a lot of
female friends. In a lot of her scenes, she is talking about a journalistic ideal or an economic
principle. Her explanations are simplified and reductive, but they get the point across. She talks
about Glass-Steagall, the Japanese radiation level announcements in March 2011, the subprime
mortgage crisis that brought about the 2008 meltdown, finding out more about a deal she knows is
happening soon and is intrigued by but doesn't know the details about, and about her new "Bloomberg
Terminal", which she uses to figure out which network a potential buyer is going to buy. In all
these scenes, her dialogue is dense, articulate, and filled with important information. There's *no
filler*, she doesn't ruminate or explore what she is about to say before coming to a
conclusion. She's there and _impatiently_ waiting for the listener (and the viewer) to catch up. I
find this kind of story-telling challenging and engaging. This is the major reason that I like
Sorkin: He turns TV, a traditionally "passive" medium, into an "active" one by forcing the viewer to
keep up or risk missing the nuance in each sentence.

I have thought about the "active" vs. "passive" medium dichotomy for a while now. After a full day
at work, I rarely used to want to read or write anything. Lately, I have been pushing myself to read
and write after work and reduce the amount of time I spend watching TV shows. This is because I want
to ensure that I am spending a big chunk of my time with active mediums, mediums that require me to
think and stay engaged, rather than passive mediums, like TV shows or online videos, which I can
turn on, tune out and let my mind wander aimlessly. Admittedly, passive media is great in some cases
(e.g. plane rides). On a daily basis though, passive mediums are best avoided.

Finally, what about the critics who say that this kind of writing / story telling / TV show making
is *"heavy-handed"*? There are several ways of making this point; one of the common tropes is to say
that Sorkin's characters are not the "Average Joe". They are *incredible*; they are at the top of
their class, they have had the best education / experience / relationships, they are confident about
who they are and what they want, they are confident that they want to remake the world and they are
sure about how they will do it, they play instruments / are talented / good with people / put other
people at ease. Another common method used to reach the same endpoint is to say that Sorkin
fetishizes intelligence: His characters are intelligent, way more than a "common" person; they have
the capability to take in a huge amount of information, such as books or dense reports with 1000s of
pages and retain almost all their life's memories, remembering everything that happened several
years ago in great detail.

Clearly, there's no doubt that Sorkin *does* this: another supporting character on the Newsroom, Jim
Harper (played by John Gallagher, Jr.) is good at his job, freaky good. He has spent time with the
US Army as a part of his reporting, he is very good at being Mackenzie's senior producer in the
studio. His experience is revered and his colleagues hold him in high regard. He plays the guitar,
and is good at getting people to talk to him. He takes stands when he feels like he has to, and
never backs down, ending with the loss of press bus privileges during a campaign and his
relationship. None of this is abrasive to me; in fact, I absolutely *want* to see Jim's point of
view, not least because I believe that I would agree with him on a lot of things. We see this in
concrete terms when his girlfriend, Hallie, gets a job at a news site called "Carnivore". Jim
notices that Hallie's contract mentions that her bonuses are tied to page views on her stories. Jim
believes that this is detrimental to journalism and incentivizes Hallie to write something that
she thinks will get views, rather than something she thinks is important and the public should
know about. Jim's uprightness about this point is painful, as he lets his relationship with Hallie
deteriorate over an ideological difference. It's important to point out that even though I agree
with Jim on his point here, I am certain that I wouldn't let it get in the way that he did. There is
a vicarious living element to relating with characters who don't back down.

I don't think the "heavy-handed" approach is a good critique. "The show is insufferable because it's
filled with characters who know too much and speak too elegantly"? That argument is flimsy to
me. *Exceptional TV shows are not filled with average people*. Average TV shows are filled with
average people. Seinfeld is not exceptional because the four main characters are run-of-the-mill;
Jon Stewart's Daily Show was an exceptional piece of comedy television, _not_ because Jon Stewart
and the correspondents (Colbert, Helms, Carell, Samantha Bee) were average; Nathan for You is a show
that is filled with average people, seen from Nathan's point of view, someone who is trying to
figure out the lengths to which people will go, when they are on TV and not really sure about the
show's goals, a decidedly uncommon thing to think about or try to televise. Expecting great
television that is filled with average characters is a fallacy. The people making these
"intelligent" shows, the characters they are writing, and the actors who are playing these
characters: _none_ of them are average, that is a necessity if they want to continue to make the
kind of TV that they do.

#+begin_export html
<hr/>
#+end_export

My advice? *Watch the show* and decide for yourself. It is likely that you will like the show. It is
equally likely that you won't like the show. Once you have made up your mind about which camp you
are in, send the two New Yorker reviews to someone who hasn't watched the show and ask them to watch
the show.
