#+TITLE: Unionized Software Engineers - Is the Social Cost spread out disproportionately?
#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: post
comments: true
title: Unionized Software Engineers - Is the Social Cost spread out disproportionately?
categories: philosophy engineering unions
---
#+end_export

#+begin_export html
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We&#39;re Alphabet workers. We’ve been organizing for over a year, &amp; we’re finally ready to share why.<br> <br>This morning, we&#39;re announcing <a href="https://twitter.com/hashtag/AWU?src=hash&amp;ref_src=twsrc%5Etfw">#AWU</a>, the first union open to *all* workers at any Alphabet company.<br> <br>Every worker deserves a union—including tech workers.<a href="https://t.co/m2Qmjwz32V">https://t.co/m2Qmjwz32V</a></p>&mdash; Alphabet Workers Union (@AlphabetWorkers) <a href="https://twitter.com/AlphabetWorkers/status/1346050124544233473?ref_src=twsrc%5Etfw">January 4, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

Today, there was [[http://archive.today/2021.01.05-004554/https://www.nytimes.com/2021/01/04/technology/google-employees-union.html][an article]] announcing a new workers union for all employees working at Alphabet,
Inc., Google's parent company, the [[https://alphabetworkersunion.org/][Alphabet Workers Union]]. The union is constituted by about 400
employees, an extremely small percentage of the total workforce of nearly 250,000 people. The union
dues are 1% of total compensation.

#+begin_quote
We still have discrimination, harassment, & retaliation at Google. Over half our workforce are
TVCs—paid less, w/fewer benefits, for often the exact same work.

...

We deserve meaningful control over the projects we work on & the direction of this company.
#+end_quote

Here's where it gets interesting: The union is a _minority union_. As the union doesn't have a
majority of all the employees as members, there is no basis for them to walk up to Alphabet's
management and demand to negotiate a Union contract. Instead, they are going to use their union as a
more abstract entity that will be used for other purposes. The question that came up when I was
discussing this with a few co-workers was whether the social cost of _this particular type of union_
is spread out disproportionately between the employer and the union members?

#+begin_export html
<!--more-->
#+end_export

I have been reading up about unions after reading [[https://www.goodreads.com/book/show/316767.The_Box?ac=1&from_search=true&qid=iD2OdIfVUf&rank=1][The Box]], _the_ book about the introduction of the
shipping container and how it took over the world. The most fascinating part of the book for me, was
the explanation of the "transition" period: the period when shipping companies, ports, and shipping
users were deciding whether to move from break-bulk shipping to container shipping. Break-bulk
shipping involves the packing and unpacking of material at each intermediate port. These packing,
unpacking, re-packing steps were carried out by dockworkers. These dockworkers were a part of unions
across the world. In some countries, they *embraced* the shipping container, deciding to improve
their skills and be a part of the crew that would help initiate the transition. In other countries,
dockworkers unions where *opposed* to the idea and did _absolutely everything_ they could to ensure
that the shipping container would not be introduced at the port that they were working at.

By "absolutely everything", I mean a set of general strikes, restrictive union agreements, and
increases in wages. One of the most fascinating clauses that one union agreement had was a clause
that each hatch on a ship would have to be manned by a minimum number of people, irrespective of the
actual amount of cargo that will be moved through that hatch. This lead to cases were the minimum
was 16 people, but only 8 people would be working at any given time. To me, this indicated *a broken
system* that was not ready to adopt new technology. Was my assessment fair? *No*, it was wrong.

Organizing to collectively bargain is a major part of the reason that a lot of workers have more
leverage over their employers actions. Unions also [[http://archive.today/2020.01.02-165305/https://www.nytimes.com/2019/12/11/us/politics/joe-biden-immigration.html][have power]] in political elections, which gives
them more attention from policy makers, and enables them to push for their policy preferences. This
system has it's advantages and can not be dismissed out-of-hand. This post will explore what is
really going on here, look at the issue from a few perspectives, and try to untangle the various
threads.

* Disproportionate social cost

From society's perspective, the negotiation between a union and the employer is a near-zero-sum
game: Union membership has some major costs, mainly, union dues that one must pay constantly, the
possibility of strikes when the union as a whole or the union leadership is unhappy with the work
conditions, and the possibility of loss-of-pay during the strike while union members are paid out a
lower stipend or given rations, using the fund maintained using their union dues.

When the union is happy, the cost is almost zero for both employee and employer. There is the union
dues cost, which is balanced out by the time that the employer spends to ensure that their policies
are not exploitative and will not anger the union enough to cause a strike.

When the union is unhappy, for a traditional union, the cost is _still_ evenly spread out: The
company loses their revenue, their ability to fill orders and a major drop in production, which will
affect their yearly output targets. Union members bear an equal cost, as they are essentially out of
a job and must now start managing with a stipend or rations; in some cases, they also need to
physically be at the picket line and spend their time there picketing. Over-all, I would say that
the cost of a traditional union during both conditions is proportionately spread out.

[[https://www.goodreads.com/book/show/50275.Last_Exit_to_Brooklyn][Selby Jr's Last Exit To Brooklyn]] is a novel that captures the mentality of a particularly lethargic
Union member (Harry) from several decades ago.

Now, take the case of the Alphabet Union: They don't have any contract. But they _do_ reserve the
right to not work on projects that they don't agree with:

#+begin_quote
All aspects of our work should be transparent, including the freedom to decline to work on projects
that don’t align with our values. We need to know the impact of our work, whether it’s on Alphabet
workers, our communities, or the world.

-- [[https://archive.vn/YkO6l#selection-628.0-628.3][Values, Alphabet Workers Union]]
#+end_quote

At this point, the costs are no longer proportionately spread out anymore. The employer can't do
much in this case (certainly not an employer like Google) because these workers are not going on
strike as a majority union. They are simply refusing to work on a particular project. Let's call
these projects that some people don't want to work on, "morally disagreeable projects".

For a large-scale company like Google, it will be extremely easy to move people around and find
people to work on any project, their pay-scale and the prestige of working at that employer is high
enough to balance out the "moral dilemma" caused by these projects. On the other hand, a
smaller-scale company which wants to get involved in a morally disagreeable project will find it
_very hard_ to staff that project.

In general, an employer who wants to work on such a project has a few options to move forward:

1) Staff the project using people who don't mind working on it OR
2) Stop working on the project

Option (1) will always be feasible for large-scale companies; they will certainly work for companies
like Alphabet. Option (2) will be the most obvious option for smaller scale companies. If the
company depends on this project for it's survival, it might go under. This in-turn will have a
ripple effect, that leads to a "bad rep" (a bad reputation) for places where such projects can not
be undertaken. Leading to newer companies attempting to work on these morally disagreeable projects
_either_ not coming up at all _or_ coming up in a different location and breaking up the Silicon
Valley hegemony on start-ups.

Either way, it is quite clear to me that the existing smaller-scale companies and future start-ups,
in the location where organizing similar to the Alphabet Union becomes popular will bear the brunt
of the burden. This disproportionate burden on one party leads me to believe that there is *a
structural problem* with the idea of a union where the costs are disproportionately shared.

* Structural-concerns
  :PROPERTIES:
  :ID:       e377901f-7241-427e-b7b2-6d00291753c8
  :END:

As we have seen, the Alphabet Union is not going to negotiate a Union contract. Instead, they are
going to exist as a body that is going to work on the sidelines. Google's current rhetoric seems to
be a complete lack of recognition for the union: Employers can insist that they will _only_ deal
with employees on an individual basis, as hinted at in this New York Times article:

#+begin_quote
In response, Kara Silverstein, Google’s director of people operations, said: “We’ve always worked
hard to create a supportive and rewarding workplace for our work force. Of course, our employees
have protected labor rights that we support. But as we’ve always done, we’ll continue engaging
directly with all our employees.”

...

Although they will not be able to negotiate a contract, the Alphabet Workers Union can use other
tactics to pressure Google into changing its policies, labor experts said. Minority unions often
turn to public pressure campaigns and lobby legislative or regulatory bodies to influence
employers.

-- [[http://archive.today/2021.01.05-004554/https://www.nytimes.com/2021/01/04/technology/google-employees-union.html][NYT article announcing the union]]
#+end_quote

In the lack of a union contract, the benefits for membership are very little. One gains some power
from the fact that this block of employees _might_ work together to push the employer into some
difficult arguments in the public sphere, but this would be no different from the public pressure
campaigns that employees at several software companies have been running over the past year as
[[https://www.msn.com/en-us/news/technology/facial-recognition-backlash-brews-after-fury-over-police-conduct/ar-BB15ZGVX][facial recognition]] and [[https://www.vox.com/recode/2019/10/9/20906605/github-ice-contract-immigration-ice-dan-friedman][software for border control agents]] have started becoming hot-button issues
with this group of people.

Furthermore, one of the biggest problems that experienced organizers identify and talk about is the
lack of incentive for the highly-skilled, focused-on-work employees to join traditional
unions. These employees tend to have good relationships with their manager, good wages and a
generally good opinion of their employer. They are the hardest to get to join the union, _and_ they
are the most important for the union, because in their absence, the union does not have legitimacy
in the employer's perspective. McAlevey talks about this at length in [[https://www.vox.com/podcasts/2020/3/17/21182149/jane-mcalevey-the-ezra-klein-show-labor-organizing][her interview on the Ezra
Klein Show]].

I believe that most software engineers work in firms where the difference in skill varies only by
their grade, and rarely has huge variations within peers who are on the same grade. In this
situation, either all the people from a given grade will have an incentive to join the union OR they
will not join the union. My bet is that the membership numbers for the Alphabet Union will stall and
they will not be able to sign-up even 10% of the total Alphabet employee base.

Finally, the other major structural concern that I came up with was the *difference in the union's
use-case*. Traditionally, unions have been used by workers who have been exploited by their
employer. The ability to bargain collectively gives these workers the kind of leverage that they
can't get if they were to negotiate their work hours or pay with their direct manager in a 1-1. This
technique has been effectively used by factory-floor workers, dockworkers, teachers to get better
pay and better work hours. In all these cases, the underlying issue is related to a concrete Labor
Law issue; this concrete connection makes the reasoning objective. On the other hand, [[id:0d597a7e-4b46-4906-9b21-60d8cd6c21ca][a morally
disagreeable project]], is ill-defined and completely subjective. The lack of objectivity makes it
very hard for the employer to predict which employees will not work on what projects (HR departments
frown on discussions about political leanings at work, although there is wide variation on this
between companies).

* What is a "morally disagreeable project"?
  :PROPERTIES:
  :ID:       0d597a7e-4b46-4906-9b21-60d8cd6c21ca
  :END:

(The subjectivity of this definition might be abundantly clear to you. If so, you can skip this
section.)

The moral nature of a project and whether it agreeable to one or not depends on their
political leanings and personal philosophy. This evaluation is bound to vary from one person to the
next, and there is no real "control" group here that can be used as a litmus test to decide whether
something is disagreeable to a majority or not (Elections are the closest we come to implementing
this mechanism, and we often don't get the result that we want, or even the result that the majority
wants if [[https://fivethirtyeight.com/videos/why-the-gop-isnt-able-to-win-the-popular-vote/?cid=rrfeaturedvideo][the system has structural problems]]).

Going further, I argue that one would be able to find _an_ argument against _any_ company that harms
either society or the environment. Several existing arguments can be re-framed as arguments that harm
people or the environment.

In the case of Amazon, the impact of 2-day shipping on the environment has been widely studied. This
Vox video condenses a bunch of the research and concepts into a short snippet.

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/5HOijUtExiM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
#+end_export

It will get tougher for employers to adjudicate whether a given project will be morally disagreeable
to the team that will work on it. The best case result of this is an employer whose limits match
exactly with their employees. The worst case is one where the employer and the employees are on
completely different sides of the spectrum, leading to _either_ pandering to ensure that attrition
stays low _or_ doing what the employer wants to do at the risk of losing talent, due to a belief
that what the employer wants to do is worthwhile.

Facebook is [[https://www.theverge.com/2019/10/1/20892354/mark-zuckerberg-full-transcript-leaked-facebook-meetings][already facing challenges]] like this one and as Mark Zuckerberg puts it, "We should
remember that Facebook's employees are much further to the left compared to Facebook's users". As
the employer, Zuckerberg and Facebook, the company *need* to focus on their users. _But_ they are also
caught in a bind with their own employees unwilling to work on a platform that they believe is
empowering the people that they don't want to empower. Casey Newton and Ezra Klein flesh this out
further on the podcast, [[https://www.theverge.com/interface/2020/2/28/21153060/social-network-polarization-ezra-klein-why-were-polarized-q-a][The Interface]].

The border line between agreeable and disagreeable is shifting frighteningly fast. The discourse has
moved a long way away from how we were talking about climate change or fossil fuel consumption
reduction or even [[https://archive.vn/fzktX#selection-336.0-336.1][fossil fuel production]] compared to 2010, only 10 years ago. The change over the
next 10 years might not be as dramatic, but there is no way to tell. Organizations that like to have
10 or 20 year plans and "roadmap" slide decks are going to have a nightmarish time figuring out _how
much_ things will change.

#+begin_export html
<hr/>
#+end_export

Over the coming months, we will see the saga of the unionized software engineers and other Alphabet
employees play out. We will also see what happens when the moral alignments of an employer and their
employees does not line up perfectly, by looking at the crisis that seems to be brewing inside
Facebook. Both of these are new phenomena that are caused due to a simultaneous increase in the
irreplaceable nature of some employees in these companies and the increase in the scale of these
companies and the incredible variety of people that their products touch.
