#+OPTIONS: author:nil toc:nil ^:nil

#+begin_export html
---
layout: page
title: About
weight: 1
---
#+end_export

Hello! My name is Siddharth Kannan. I am a Site Reliability Engineer at [[https://www.mercari.com/][Mercari]]. I have been living
in Tokyo, Japan since October 2018. This is my blog, and I have been writing posts here
since 2014. I write primarily about the books I read, the music I listen to, and the code I write in
my free time. I have also written sporadically about the Internet and the ways in which products
online attempt to keep their users engaged through recommendation systems that peddle salacious
content.

I wrote on [[https://blog.siddharthkannan.in/2017/03/26/day-37][various bloging platforms]] before settling on this page.

I love Golang and Docker, and I package all my personal deployments into a Docker container. I use
Bash, along with tools such as =awk= and =sed=, for most of my scripting needs. I have worked
extensively with PHP and MySQL while working on a [[https://en.wikipedia.org/wiki/LAMP_(software_bundle)][LAMP stack]] application at work. I use Nginx as the
reverse proxy for applications running on my cloud VMs.

My computer is running the latest version of Debian with GNOME and i3 as window managers. I switched
to Debian relatively recently, after years of using Ubuntu, to get away from the [[https://gist.github.com/NickSeagull/ed43a80db6a54d69ded3e18f8babaf19][increasing
bloatware]] in that distribution. I love tiling window managers in general and i3 in particular;
however, I have kept Gnome around as a replacement for workflows that I have not yet mastered on
i3.[fn:1]

Firefox, tmux, git, and Emacs are the major parts of my daily setup. I switched from Vim to Emacs [[https://blog.siddharthkannan.in/2020/07/08/vim-and-emacs][4
years ago]] and it has been the most rewarding tooling change for me. I use Org mode and [[https://github.com/org-roam/org-roam][org-roam]] for
note taking at home and at work. I use Wireguard for self-managed VPN instances, as well as for a
private network, where I have deployed applications such as [[https://github.com/miniflux/v2][Miniflux]] (RSS feed reader) and [[https://github.com/go-shiori/shiori][Shiori]]
(bookmark manager).

I play a few games (semi-regularly) on an old Playstation 4. The list includes Fortnite, Last of Us
and Civilization 6. I highly recommend Civilization 6 to anyone who likes to read history. I am
constantly amazed by the performance that the PS4 can deliver nearly 8 years after its original
release.

You can check out some of my open-source projects on [[https://github.com/icyflame][GitHub]].

If you want to contact me, you can send an e-mail to =mail [at] siddharthkannan [dot] in=.

-----

/Last updated: 2024-09-16/

* Footnotes

[fn:1] Now, this includes audio and bluetooth devices, both of which seem to have spotty support
despite PulseAudio / Pipewire and applications like Blueman.
